/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Layer2BasicInfo,
  ResultCode,
} from '../models/index';
import {
    Layer2BasicInfoFromJSON,
    Layer2BasicInfoToJSON,
    ResultCodeFromJSON,
    ResultCodeToJSON,
} from '../models/index';

/**
 * InfoApi - interface
 * 
 * @export
 * @interface InfoApiInterface
 */
export interface InfoApiInterface {
    /**
     * Get zklighter general info, including contract address, and count of transactions and active users
     * @summary layer2BasicInfo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InfoApiInterface
     */
    layer2BasicInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Layer2BasicInfo>>;

    /**
     * Get zklighter general info, including contract address, and count of transactions and active users
     * layer2BasicInfo
     */
    layer2BasicInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Layer2BasicInfo>;

}

/**
 * 
 */
export class InfoApi extends runtime.BaseAPI implements InfoApiInterface {

    /**
     * Get zklighter general info, including contract address, and count of transactions and active users
     * layer2BasicInfo
     */
    async layer2BasicInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Layer2BasicInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/layer2BasicInfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Layer2BasicInfoFromJSON(jsonValue));
    }

    /**
     * Get zklighter general info, including contract address, and count of transactions and active users
     * layer2BasicInfo
     */
    async layer2BasicInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Layer2BasicInfo> {
        const response = await this.layer2BasicInfoRaw(initOverrides);
        return await response.value();
    }

}
