/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKey } from './ApiKey';
import {
    ApiKeyFromJSON,
    ApiKeyFromJSONTyped,
    ApiKeyToJSON,
    ApiKeyToJSONTyped,
} from './ApiKey';

/**
 * 
 * @export
 * @interface AccountApiKeys
 */
export interface AccountApiKeys {
    /**
     * 
     * @type {number}
     * @memberof AccountApiKeys
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof AccountApiKeys
     */
    message?: string;
    /**
     * 
     * @type {Array<ApiKey>}
     * @memberof AccountApiKeys
     */
    apiKeys: Array<ApiKey>;
}

/**
 * Check if a given object implements the AccountApiKeys interface.
 */
export function instanceOfAccountApiKeys(value: object): value is AccountApiKeys {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('apiKeys' in value) || value['apiKeys'] === undefined) return false;
    return true;
}

export function AccountApiKeysFromJSON(json: any): AccountApiKeys {
    return AccountApiKeysFromJSONTyped(json, false);
}

export function AccountApiKeysFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountApiKeys {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'apiKeys': ((json['api_keys'] as Array<any>).map(ApiKeyFromJSON)),
    };
}

export function AccountApiKeysToJSON(json: any): AccountApiKeys {
    return AccountApiKeysToJSONTyped(json, false);
}

export function AccountApiKeysToJSONTyped(value?: AccountApiKeys | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'api_keys': ((value['apiKeys'] as Array<any>).map(ApiKeyToJSON)),
    };
}

