/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountStats
 */
export interface AccountStats {
    /**
     * 
     * @type {string}
     * @memberof AccountStats
     */
    collateral: string;
    /**
     * 
     * @type {string}
     * @memberof AccountStats
     */
    portfolioValue: string;
    /**
     * 
     * @type {string}
     * @memberof AccountStats
     */
    leverage: string;
    /**
     * 
     * @type {string}
     * @memberof AccountStats
     */
    availableBalance: string;
    /**
     * 
     * @type {string}
     * @memberof AccountStats
     */
    marginUsage: string;
    /**
     * 
     * @type {string}
     * @memberof AccountStats
     */
    buyingPower: string;
}

/**
 * Check if a given object implements the AccountStats interface.
 */
export function instanceOfAccountStats(value: object): value is AccountStats {
    if (!('collateral' in value) || value['collateral'] === undefined) return false;
    if (!('portfolioValue' in value) || value['portfolioValue'] === undefined) return false;
    if (!('leverage' in value) || value['leverage'] === undefined) return false;
    if (!('availableBalance' in value) || value['availableBalance'] === undefined) return false;
    if (!('marginUsage' in value) || value['marginUsage'] === undefined) return false;
    if (!('buyingPower' in value) || value['buyingPower'] === undefined) return false;
    return true;
}

export function AccountStatsFromJSON(json: any): AccountStats {
    return AccountStatsFromJSONTyped(json, false);
}

export function AccountStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountStats {
    if (json == null) {
        return json;
    }
    return {
        
        'collateral': json['collateral'],
        'portfolioValue': json['portfolio_value'],
        'leverage': json['leverage'],
        'availableBalance': json['available_balance'],
        'marginUsage': json['margin_usage'],
        'buyingPower': json['buying_power'],
    };
}

export function AccountStatsToJSON(json: any): AccountStats {
    return AccountStatsToJSONTyped(json, false);
}

export function AccountStatsToJSONTyped(value?: AccountStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collateral': value['collateral'],
        'portfolio_value': value['portfolioValue'],
        'leverage': value['leverage'],
        'available_balance': value['availableBalance'],
        'margin_usage': value['marginUsage'],
        'buying_power': value['buyingPower'],
    };
}

