/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountMetadata
 */
export interface AccountMetadata {
    /**
     * 
     * @type {string}
     * @memberof AccountMetadata
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AccountMetadata
     */
    description: string;
}

/**
 * Check if a given object implements the AccountMetadata interface.
 */
export function instanceOfAccountMetadata(value: object): value is AccountMetadata {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function AccountMetadataFromJSON(json: any): AccountMetadata {
    return AccountMetadataFromJSONTyped(json, false);
}

export function AccountMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function AccountMetadataToJSON(json: any): AccountMetadata {
    return AccountMetadataToJSONTyped(json, false);
}

export function AccountMetadataToJSONTyped(value?: AccountMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

