/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 * 
 * @export
 * @interface Accounts
 */
export interface Accounts {
    /**
     * 
     * @type {number}
     * @memberof Accounts
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof Accounts
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof Accounts
     */
    total: number;
    /**
     * 
     * @type {Array<Account>}
     * @memberof Accounts
     */
    accounts: Array<Account>;
}

/**
 * Check if a given object implements the Accounts interface.
 */
export function instanceOfAccounts(value: object): value is Accounts {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function AccountsFromJSON(json: any): Accounts {
    return AccountsFromJSONTyped(json, false);
}

export function AccountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Accounts {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'total': json['total'],
        'accounts': ((json['accounts'] as Array<any>).map(AccountFromJSON)),
    };
}

export function AccountsToJSON(json: any): Accounts {
    return AccountsToJSONTyped(json, false);
}

export function AccountsToJSONTyped(value?: Accounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'total': value['total'],
        'accounts': ((value['accounts'] as Array<any>).map(AccountToJSON)),
    };
}

