/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BridgeSupportedNetwork
 */
export interface BridgeSupportedNetwork {
    /**
     * 
     * @type {string}
     * @memberof BridgeSupportedNetwork
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BridgeSupportedNetwork
     */
    chainId: string;
    /**
     * 
     * @type {string}
     * @memberof BridgeSupportedNetwork
     */
    explorer: string;
}

/**
 * Check if a given object implements the BridgeSupportedNetwork interface.
 */
export function instanceOfBridgeSupportedNetwork(value: object): value is BridgeSupportedNetwork {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('chainId' in value) || value['chainId'] === undefined) return false;
    if (!('explorer' in value) || value['explorer'] === undefined) return false;
    return true;
}

export function BridgeSupportedNetworkFromJSON(json: any): BridgeSupportedNetwork {
    return BridgeSupportedNetworkFromJSONTyped(json, false);
}

export function BridgeSupportedNetworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): BridgeSupportedNetwork {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'chainId': json['chain_id'],
        'explorer': json['explorer'],
    };
}

export function BridgeSupportedNetworkToJSON(json: any): BridgeSupportedNetwork {
    return BridgeSupportedNetworkToJSONTyped(json, false);
}

export function BridgeSupportedNetworkToJSONTyped(value?: BridgeSupportedNetwork | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'chain_id': value['chainId'],
        'explorer': value['explorer'],
    };
}

