/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Cursor
 */
export interface Cursor {
    /**
     * 
     * @type {string}
     * @memberof Cursor
     */
    nextCursor?: string;
}

/**
 * Check if a given object implements the Cursor interface.
 */
export function instanceOfCursor(value: object): value is Cursor {
    return true;
}

export function CursorFromJSON(json: any): Cursor {
    return CursorFromJSONTyped(json, false);
}

export function CursorFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cursor {
    if (json == null) {
        return json;
    }
    return {
        
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
    };
}

export function CursorToJSON(json: any): Cursor {
    return CursorToJSONTyped(json, false);
}

export function CursorToJSONTyped(value?: Cursor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next_cursor': value['nextCursor'],
    };
}

