/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepositHistoryItem
 */
export interface DepositHistoryItem {
    /**
     * 
     * @type {string}
     * @memberof DepositHistoryItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DepositHistoryItem
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof DepositHistoryItem
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof DepositHistoryItem
     */
    status: DepositHistoryItemStatusEnum;
}


/**
 * @export
 */
export const DepositHistoryItemStatusEnum = {
    failed: 'failed',
    pending: 'pending',
    completed: 'completed'
} as const;
export type DepositHistoryItemStatusEnum = typeof DepositHistoryItemStatusEnum[keyof typeof DepositHistoryItemStatusEnum];


/**
 * Check if a given object implements the DepositHistoryItem interface.
 */
export function instanceOfDepositHistoryItem(value: object): value is DepositHistoryItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DepositHistoryItemFromJSON(json: any): DepositHistoryItem {
    return DepositHistoryItemFromJSONTyped(json, false);
}

export function DepositHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositHistoryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'timestamp': json['timestamp'],
        'status': json['status'],
    };
}

export function DepositHistoryItemToJSON(json: any): DepositHistoryItem {
    return DepositHistoryItemToJSONTyped(json, false);
}

export function DepositHistoryItemToJSONTyped(value?: DepositHistoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'timestamp': value['timestamp'],
        'status': value['status'],
    };
}

