/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailedCandlestick
 */
export interface DetailedCandlestick {
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    timestamp: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    open: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    high: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    low: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    close: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    volume0: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    volume1: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    lastTradeId: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedCandlestick
     */
    tradeCount: number;
}

/**
 * Check if a given object implements the DetailedCandlestick interface.
 */
export function instanceOfDetailedCandlestick(value: object): value is DetailedCandlestick {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('open' in value) || value['open'] === undefined) return false;
    if (!('high' in value) || value['high'] === undefined) return false;
    if (!('low' in value) || value['low'] === undefined) return false;
    if (!('close' in value) || value['close'] === undefined) return false;
    if (!('volume0' in value) || value['volume0'] === undefined) return false;
    if (!('volume1' in value) || value['volume1'] === undefined) return false;
    if (!('lastTradeId' in value) || value['lastTradeId'] === undefined) return false;
    if (!('tradeCount' in value) || value['tradeCount'] === undefined) return false;
    return true;
}

export function DetailedCandlestickFromJSON(json: any): DetailedCandlestick {
    return DetailedCandlestickFromJSONTyped(json, false);
}

export function DetailedCandlestickFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedCandlestick {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'open': json['open'],
        'high': json['high'],
        'low': json['low'],
        'close': json['close'],
        'volume0': json['volume0'],
        'volume1': json['volume1'],
        'lastTradeId': json['last_trade_id'],
        'tradeCount': json['trade_count'],
    };
}

export function DetailedCandlestickToJSON(json: any): DetailedCandlestick {
    return DetailedCandlestickToJSONTyped(json, false);
}

export function DetailedCandlestickToJSONTyped(value?: DetailedCandlestick | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'open': value['open'],
        'high': value['high'],
        'low': value['low'],
        'close': value['close'],
        'volume0': value['volume0'],
        'volume1': value['volume1'],
        'last_trade_id': value['lastTradeId'],
        'trade_count': value['tradeCount'],
    };
}

