/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailedAccount } from './DetailedAccount';
import {
    DetailedAccountFromJSON,
    DetailedAccountFromJSONTyped,
    DetailedAccountToJSON,
    DetailedAccountToJSONTyped,
} from './DetailedAccount';

/**
 * 
 * @export
 * @interface DetailedAccounts
 */
export interface DetailedAccounts {
    /**
     * 
     * @type {number}
     * @memberof DetailedAccounts
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof DetailedAccounts
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof DetailedAccounts
     */
    total: number;
    /**
     * 
     * @type {Array<DetailedAccount>}
     * @memberof DetailedAccounts
     */
    accounts: Array<DetailedAccount>;
}

/**
 * Check if a given object implements the DetailedAccounts interface.
 */
export function instanceOfDetailedAccounts(value: object): value is DetailedAccounts {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    return true;
}

export function DetailedAccountsFromJSON(json: any): DetailedAccounts {
    return DetailedAccountsFromJSONTyped(json, false);
}

export function DetailedAccountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedAccounts {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'total': json['total'],
        'accounts': ((json['accounts'] as Array<any>).map(DetailedAccountFromJSON)),
    };
}

export function DetailedAccountsToJSON(json: any): DetailedAccounts {
    return DetailedAccountsToJSONTyped(json, false);
}

export function DetailedAccountsToJSONTyped(value?: DetailedAccounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'total': value['total'],
        'accounts': ((value['accounts'] as Array<any>).map(DetailedAccountToJSON)),
    };
}

