/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderBookStats } from './OrderBookStats';
import {
    OrderBookStatsFromJSON,
    OrderBookStatsFromJSONTyped,
    OrderBookStatsToJSON,
    OrderBookStatsToJSONTyped,
} from './OrderBookStats';

/**
 * 
 * @export
 * @interface ExchangeStats
 */
export interface ExchangeStats {
    /**
     * 
     * @type {number}
     * @memberof ExchangeStats
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof ExchangeStats
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ExchangeStats
     */
    total: number;
    /**
     * 
     * @type {Array<OrderBookStats>}
     * @memberof ExchangeStats
     */
    orderBookStats: Array<OrderBookStats>;
    /**
     * 
     * @type {number}
     * @memberof ExchangeStats
     */
    dailyUsdVolume: number;
    /**
     * 
     * @type {number}
     * @memberof ExchangeStats
     */
    dailyTradesCount: number;
}

/**
 * Check if a given object implements the ExchangeStats interface.
 */
export function instanceOfExchangeStats(value: object): value is ExchangeStats {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('orderBookStats' in value) || value['orderBookStats'] === undefined) return false;
    if (!('dailyUsdVolume' in value) || value['dailyUsdVolume'] === undefined) return false;
    if (!('dailyTradesCount' in value) || value['dailyTradesCount'] === undefined) return false;
    return true;
}

export function ExchangeStatsFromJSON(json: any): ExchangeStats {
    return ExchangeStatsFromJSONTyped(json, false);
}

export function ExchangeStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeStats {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'total': json['total'],
        'orderBookStats': ((json['order_book_stats'] as Array<any>).map(OrderBookStatsFromJSON)),
        'dailyUsdVolume': json['daily_usd_volume'],
        'dailyTradesCount': json['daily_trades_count'],
    };
}

export function ExchangeStatsToJSON(json: any): ExchangeStats {
    return ExchangeStatsToJSONTyped(json, false);
}

export function ExchangeStatsToJSONTyped(value?: ExchangeStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'total': value['total'],
        'order_book_stats': ((value['orderBookStats'] as Array<any>).map(OrderBookStatsToJSON)),
        'daily_usd_volume': value['dailyUsdVolume'],
        'daily_trades_count': value['dailyTradesCount'],
    };
}

