/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeeBucket
 */
export interface FeeBucket {
    /**
     * 
     * @type {number}
     * @memberof FeeBucket
     */
    vipTier: number;
    /**
     * 
     * @type {number}
     * @memberof FeeBucket
     */
    takerFee: number;
    /**
     * 
     * @type {number}
     * @memberof FeeBucket
     */
    makerFee: number;
}

/**
 * Check if a given object implements the FeeBucket interface.
 */
export function instanceOfFeeBucket(value: object): value is FeeBucket {
    if (!('vipTier' in value) || value['vipTier'] === undefined) return false;
    if (!('takerFee' in value) || value['takerFee'] === undefined) return false;
    if (!('makerFee' in value) || value['makerFee'] === undefined) return false;
    return true;
}

export function FeeBucketFromJSON(json: any): FeeBucket {
    return FeeBucketFromJSONTyped(json, false);
}

export function FeeBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeeBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'vipTier': json['vip_tier'],
        'takerFee': json['taker_fee'],
        'makerFee': json['maker_fee'],
    };
}

export function FeeBucketToJSON(json: any): FeeBucket {
    return FeeBucketToJSONTyped(json, false);
}

export function FeeBucketToJSONTyped(value?: FeeBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vip_tier': value['vipTier'],
        'taker_fee': value['takerFee'],
        'maker_fee': value['makerFee'],
    };
}

