/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Funding
 */
export interface Funding {
    /**
     * 
     * @type {number}
     * @memberof Funding
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof Funding
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof Funding
     */
    rate: string;
    /**
     * 
     * @type {string}
     * @memberof Funding
     */
    direction: string;
}

/**
 * Check if a given object implements the Funding interface.
 */
export function instanceOfFunding(value: object): value is Funding {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    return true;
}

export function FundingFromJSON(json: any): Funding {
    return FundingFromJSONTyped(json, false);
}

export function FundingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Funding {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'value': json['value'],
        'rate': json['rate'],
        'direction': json['direction'],
    };
}

export function FundingToJSON(json: any): Funding {
    return FundingToJSONTyped(json, false);
}

export function FundingToJSONTyped(value?: Funding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'value': value['value'],
        'rate': value['rate'],
        'direction': value['direction'],
    };
}

