/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Layer2BasicInfo
 */
export interface Layer2BasicInfo {
    /**
     * 
     * @type {number}
     * @memberof Layer2BasicInfo
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof Layer2BasicInfo
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof Layer2BasicInfo
     */
    blockCommitted: number;
    /**
     * 
     * @type {number}
     * @memberof Layer2BasicInfo
     */
    blockVerified: number;
    /**
     * 
     * @type {number}
     * @memberof Layer2BasicInfo
     */
    totalTransactionCount: number;
}

/**
 * Check if a given object implements the Layer2BasicInfo interface.
 */
export function instanceOfLayer2BasicInfo(value: object): value is Layer2BasicInfo {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('blockCommitted' in value) || value['blockCommitted'] === undefined) return false;
    if (!('blockVerified' in value) || value['blockVerified'] === undefined) return false;
    if (!('totalTransactionCount' in value) || value['totalTransactionCount'] === undefined) return false;
    return true;
}

export function Layer2BasicInfoFromJSON(json: any): Layer2BasicInfo {
    return Layer2BasicInfoFromJSONTyped(json, false);
}

export function Layer2BasicInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Layer2BasicInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'blockCommitted': json['block_committed'],
        'blockVerified': json['block_verified'],
        'totalTransactionCount': json['total_transaction_count'],
    };
}

export function Layer2BasicInfoToJSON(json: any): Layer2BasicInfo {
    return Layer2BasicInfoToJSONTyped(json, false);
}

export function Layer2BasicInfoToJSONTyped(value?: Layer2BasicInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'block_committed': value['blockCommitted'],
        'block_verified': value['blockVerified'],
        'total_transaction_count': value['totalTransactionCount'],
    };
}

