/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NextNonce
 */
export interface NextNonce {
    /**
     * 
     * @type {number}
     * @memberof NextNonce
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof NextNonce
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof NextNonce
     */
    nonce: number;
}

/**
 * Check if a given object implements the NextNonce interface.
 */
export function instanceOfNextNonce(value: object): value is NextNonce {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    return true;
}

export function NextNonceFromJSON(json: any): NextNonce {
    return NextNonceFromJSONTyped(json, false);
}

export function NextNonceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NextNonce {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'nonce': json['nonce'],
    };
}

export function NextNonceToJSON(json: any): NextNonce {
    return NextNonceToJSONTyped(json, false);
}

export function NextNonceToJSONTyped(value?: NextNonce | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'nonce': value['nonce'],
    };
}

