/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleOrder } from './SimpleOrder';
import {
    SimpleOrderFromJSON,
    SimpleOrderFromJSONTyped,
    SimpleOrderToJSON,
    SimpleOrderToJSONTyped,
} from './SimpleOrder';

/**
 * 
 * @export
 * @interface OrderBookOrders
 */
export interface OrderBookOrders {
    /**
     * 
     * @type {number}
     * @memberof OrderBookOrders
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof OrderBookOrders
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderBookOrders
     */
    totalAsks: number;
    /**
     * 
     * @type {Array<SimpleOrder>}
     * @memberof OrderBookOrders
     */
    asks: Array<SimpleOrder>;
    /**
     * 
     * @type {number}
     * @memberof OrderBookOrders
     */
    totalBids: number;
    /**
     * 
     * @type {Array<SimpleOrder>}
     * @memberof OrderBookOrders
     */
    bids: Array<SimpleOrder>;
}

/**
 * Check if a given object implements the OrderBookOrders interface.
 */
export function instanceOfOrderBookOrders(value: object): value is OrderBookOrders {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('totalAsks' in value) || value['totalAsks'] === undefined) return false;
    if (!('asks' in value) || value['asks'] === undefined) return false;
    if (!('totalBids' in value) || value['totalBids'] === undefined) return false;
    if (!('bids' in value) || value['bids'] === undefined) return false;
    return true;
}

export function OrderBookOrdersFromJSON(json: any): OrderBookOrders {
    return OrderBookOrdersFromJSONTyped(json, false);
}

export function OrderBookOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBookOrders {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'totalAsks': json['total_asks'],
        'asks': ((json['asks'] as Array<any>).map(SimpleOrderFromJSON)),
        'totalBids': json['total_bids'],
        'bids': ((json['bids'] as Array<any>).map(SimpleOrderFromJSON)),
    };
}

export function OrderBookOrdersToJSON(json: any): OrderBookOrders {
    return OrderBookOrdersToJSONTyped(json, false);
}

export function OrderBookOrdersToJSONTyped(value?: OrderBookOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'total_asks': value['totalAsks'],
        'asks': ((value['asks'] as Array<any>).map(SimpleOrderToJSON)),
        'total_bids': value['totalBids'],
        'bids': ((value['bids'] as Array<any>).map(SimpleOrderToJSON)),
    };
}

