/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderBookStats
 */
export interface OrderBookStats {
    /**
     * 
     * @type {string}
     * @memberof OrderBookStats
     */
    symbol: string;
    /**
     * 
     * @type {number}
     * @memberof OrderBookStats
     */
    lastTradePrice: number;
    /**
     * 
     * @type {number}
     * @memberof OrderBookStats
     */
    dailyTradesCount: number;
    /**
     * 
     * @type {number}
     * @memberof OrderBookStats
     */
    dailyBaseTokenVolume: number;
    /**
     * 
     * @type {number}
     * @memberof OrderBookStats
     */
    dailyQuoteTokenVolume: number;
    /**
     * 
     * @type {number}
     * @memberof OrderBookStats
     */
    dailyPriceChange: number;
}

/**
 * Check if a given object implements the OrderBookStats interface.
 */
export function instanceOfOrderBookStats(value: object): value is OrderBookStats {
    if (!('symbol' in value) || value['symbol'] === undefined) return false;
    if (!('lastTradePrice' in value) || value['lastTradePrice'] === undefined) return false;
    if (!('dailyTradesCount' in value) || value['dailyTradesCount'] === undefined) return false;
    if (!('dailyBaseTokenVolume' in value) || value['dailyBaseTokenVolume'] === undefined) return false;
    if (!('dailyQuoteTokenVolume' in value) || value['dailyQuoteTokenVolume'] === undefined) return false;
    if (!('dailyPriceChange' in value) || value['dailyPriceChange'] === undefined) return false;
    return true;
}

export function OrderBookStatsFromJSON(json: any): OrderBookStats {
    return OrderBookStatsFromJSONTyped(json, false);
}

export function OrderBookStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBookStats {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'lastTradePrice': json['last_trade_price'],
        'dailyTradesCount': json['daily_trades_count'],
        'dailyBaseTokenVolume': json['daily_base_token_volume'],
        'dailyQuoteTokenVolume': json['daily_quote_token_volume'],
        'dailyPriceChange': json['daily_price_change'],
    };
}

export function OrderBookStatsToJSON(json: any): OrderBookStats {
    return OrderBookStatsToJSONTyped(json, false);
}

export function OrderBookStatsToJSONTyped(value?: OrderBookStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'symbol': value['symbol'],
        'last_trade_price': value['lastTradePrice'],
        'daily_trades_count': value['dailyTradesCount'],
        'daily_base_token_volume': value['dailyBaseTokenVolume'],
        'daily_quote_token_volume': value['dailyQuoteTokenVolume'],
        'daily_price_change': value['dailyPriceChange'],
    };
}

