/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderBookDetail } from './OrderBookDetail';
import {
    OrderBookDetailFromJSON,
    OrderBookDetailFromJSONTyped,
    OrderBookDetailToJSON,
    OrderBookDetailToJSONTyped,
} from './OrderBookDetail';

/**
 * 
 * @export
 * @interface OrderBookDetails
 */
export interface OrderBookDetails {
    /**
     * 
     * @type {number}
     * @memberof OrderBookDetails
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof OrderBookDetails
     */
    message?: string;
    /**
     * 
     * @type {Array<OrderBookDetail>}
     * @memberof OrderBookDetails
     */
    orderBookDetails: Array<OrderBookDetail>;
}

/**
 * Check if a given object implements the OrderBookDetails interface.
 */
export function instanceOfOrderBookDetails(value: object): value is OrderBookDetails {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('orderBookDetails' in value) || value['orderBookDetails'] === undefined) return false;
    return true;
}

export function OrderBookDetailsFromJSON(json: any): OrderBookDetails {
    return OrderBookDetailsFromJSONTyped(json, false);
}

export function OrderBookDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBookDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'orderBookDetails': ((json['order_book_details'] as Array<any>).map(OrderBookDetailFromJSON)),
    };
}

export function OrderBookDetailsToJSON(json: any): OrderBookDetails {
    return OrderBookDetailsToJSONTyped(json, false);
}

export function OrderBookDetailsToJSONTyped(value?: OrderBookDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'order_book_details': ((value['orderBookDetails'] as Array<any>).map(OrderBookDetailToJSON)),
    };
}

