/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicPoolShare
 */
export interface PublicPoolShare {
    /**
     * 
     * @type {number}
     * @memberof PublicPoolShare
     */
    publicPoolIndex: number;
    /**
     * 
     * @type {number}
     * @memberof PublicPoolShare
     */
    sharesAmount: number;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolShare
     */
    entryUsdc: string;
}

/**
 * Check if a given object implements the PublicPoolShare interface.
 */
export function instanceOfPublicPoolShare(value: object): value is PublicPoolShare {
    if (!('publicPoolIndex' in value) || value['publicPoolIndex'] === undefined) return false;
    if (!('sharesAmount' in value) || value['sharesAmount'] === undefined) return false;
    if (!('entryUsdc' in value) || value['entryUsdc'] === undefined) return false;
    return true;
}

export function PublicPoolShareFromJSON(json: any): PublicPoolShare {
    return PublicPoolShareFromJSONTyped(json, false);
}

export function PublicPoolShareFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPoolShare {
    if (json == null) {
        return json;
    }
    return {
        
        'publicPoolIndex': json['public_pool_index'],
        'sharesAmount': json['shares_amount'],
        'entryUsdc': json['entry_usdc'],
    };
}

export function PublicPoolShareToJSON(json: any): PublicPoolShare {
    return PublicPoolShareToJSONTyped(json, false);
}

export function PublicPoolShareToJSONTyped(value?: PublicPoolShare | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_pool_index': value['publicPoolIndex'],
        'shares_amount': value['sharesAmount'],
        'entry_usdc': value['entryUsdc'],
    };
}

