/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicPoolInfo
 */
export interface PublicPoolInfo {
    /**
     * 
     * @type {number}
     * @memberof PublicPoolInfo
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolInfo
     */
    operatorFee: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPoolInfo
     */
    minOperatorShareRate: string;
    /**
     * 
     * @type {number}
     * @memberof PublicPoolInfo
     */
    totalShares: number;
    /**
     * 
     * @type {number}
     * @memberof PublicPoolInfo
     */
    operatorShares: number;
}

/**
 * Check if a given object implements the PublicPoolInfo interface.
 */
export function instanceOfPublicPoolInfo(value: object): value is PublicPoolInfo {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('operatorFee' in value) || value['operatorFee'] === undefined) return false;
    if (!('minOperatorShareRate' in value) || value['minOperatorShareRate'] === undefined) return false;
    if (!('totalShares' in value) || value['totalShares'] === undefined) return false;
    if (!('operatorShares' in value) || value['operatorShares'] === undefined) return false;
    return true;
}

export function PublicPoolInfoFromJSON(json: any): PublicPoolInfo {
    return PublicPoolInfoFromJSONTyped(json, false);
}

export function PublicPoolInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPoolInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'operatorFee': json['operator_fee'],
        'minOperatorShareRate': json['min_operator_share_rate'],
        'totalShares': json['total_shares'],
        'operatorShares': json['operator_shares'],
    };
}

export function PublicPoolInfoToJSON(json: any): PublicPoolInfo {
    return PublicPoolInfoToJSONTyped(json, false);
}

export function PublicPoolInfoToJSONTyped(value?: PublicPoolInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'operator_fee': value['operatorFee'],
        'min_operator_share_rate': value['minOperatorShareRate'],
        'total_shares': value['totalShares'],
        'operator_shares': value['operatorShares'],
    };
}

