/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetByAccount
 */
export interface ReqGetByAccount {
    /**
     * 
     * @type {string}
     * @memberof ReqGetByAccount
     */
    by: ReqGetByAccountByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetByAccount
     */
    value: string;
}


/**
 * @export
 */
export const ReqGetByAccountByEnum = {
    accountIndex: 'account_index'
} as const;
export type ReqGetByAccountByEnum = typeof ReqGetByAccountByEnum[keyof typeof ReqGetByAccountByEnum];


/**
 * Check if a given object implements the ReqGetByAccount interface.
 */
export function instanceOfReqGetByAccount(value: object): value is ReqGetByAccount {
    if (!('by' in value) || value['by'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ReqGetByAccountFromJSON(json: any): ReqGetByAccount {
    return ReqGetByAccountFromJSONTyped(json, false);
}

export function ReqGetByAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetByAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'by': json['by'],
        'value': json['value'],
    };
}

export function ReqGetByAccountToJSON(json: any): ReqGetByAccount {
    return ReqGetByAccountToJSONTyped(json, false);
}

export function ReqGetByAccountToJSONTyped(value?: ReqGetByAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by': value['by'],
        'value': value['value'],
    };
}

