/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetOrderBookDetails
 */
export interface ReqGetOrderBookDetails {
    /**
     * 
     * @type {number}
     * @memberof ReqGetOrderBookDetails
     */
    marketId?: number;
}

/**
 * Check if a given object implements the ReqGetOrderBookDetails interface.
 */
export function instanceOfReqGetOrderBookDetails(value: object): value is ReqGetOrderBookDetails {
    return true;
}

export function ReqGetOrderBookDetailsFromJSON(json: any): ReqGetOrderBookDetails {
    return ReqGetOrderBookDetailsFromJSONTyped(json, false);
}

export function ReqGetOrderBookDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetOrderBookDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'marketId': json['market_id'] == null ? undefined : json['market_id'],
    };
}

export function ReqGetOrderBookDetailsToJSON(json: any): ReqGetOrderBookDetails {
    return ReqGetOrderBookDetailsToJSONTyped(json, false);
}

export function ReqGetOrderBookDetailsToJSONTyped(value?: ReqGetOrderBookDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_id': value['marketId'],
    };
}

