/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetAccountTxs
 */
export interface ReqGetAccountTxs {
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountTxs
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountTxs
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountTxs
     */
    by?: ReqGetAccountTxsByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountTxs
     */
    value?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ReqGetAccountTxs
     */
    types?: Array<number>;
}


/**
 * @export
 */
export const ReqGetAccountTxsByEnum = {
    accountIndex: 'account_index'
} as const;
export type ReqGetAccountTxsByEnum = typeof ReqGetAccountTxsByEnum[keyof typeof ReqGetAccountTxsByEnum];


/**
 * Check if a given object implements the ReqGetAccountTxs interface.
 */
export function instanceOfReqGetAccountTxs(value: object): value is ReqGetAccountTxs {
    return true;
}

export function ReqGetAccountTxsFromJSON(json: any): ReqGetAccountTxs {
    return ReqGetAccountTxsFromJSONTyped(json, false);
}

export function ReqGetAccountTxsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAccountTxs {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'by': json['by'] == null ? undefined : json['by'],
        'value': json['value'] == null ? undefined : json['value'],
        'types': json['types'] == null ? undefined : json['types'],
    };
}

export function ReqGetAccountTxsToJSON(json: any): ReqGetAccountTxs {
    return ReqGetAccountTxsToJSONTyped(json, false);
}

export function ReqGetAccountTxsToJSONTyped(value?: ReqGetAccountTxs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'limit': value['limit'],
        'by': value['by'],
        'value': value['value'],
        'types': value['types'],
    };
}

