/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetTx
 */
export interface ReqGetTx {
    /**
     * 
     * @type {string}
     * @memberof ReqGetTx
     */
    by: ReqGetTxByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetTx
     */
    value: string;
}


/**
 * @export
 */
export const ReqGetTxByEnum = {
    hash: 'hash',
    sequenceIndex: 'sequence_index'
} as const;
export type ReqGetTxByEnum = typeof ReqGetTxByEnum[keyof typeof ReqGetTxByEnum];


/**
 * Check if a given object implements the ReqGetTx interface.
 */
export function instanceOfReqGetTx(value: object): value is ReqGetTx {
    if (!('by' in value) || value['by'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ReqGetTxFromJSON(json: any): ReqGetTx {
    return ReqGetTxFromJSONTyped(json, false);
}

export function ReqGetTxFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetTx {
    if (json == null) {
        return json;
    }
    return {
        
        'by': json['by'],
        'value': json['value'],
    };
}

export function ReqGetTxToJSON(json: any): ReqGetTx {
    return ReqGetTxToJSONTyped(json, false);
}

export function ReqGetTxToJSONTyped(value?: ReqGetTx | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by': value['by'],
        'value': value['value'],
    };
}

