/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetOrderBooks
 */
export interface ReqGetOrderBooks {
    /**
     * 
     * @type {number}
     * @memberof ReqGetOrderBooks
     */
    marketId?: number;
}

/**
 * Check if a given object implements the ReqGetOrderBooks interface.
 */
export function instanceOfReqGetOrderBooks(value: object): value is ReqGetOrderBooks {
    return true;
}

export function ReqGetOrderBooksFromJSON(json: any): ReqGetOrderBooks {
    return ReqGetOrderBooksFromJSONTyped(json, false);
}

export function ReqGetOrderBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetOrderBooks {
    if (json == null) {
        return json;
    }
    return {
        
        'marketId': json['market_id'] == null ? undefined : json['market_id'],
    };
}

export function ReqGetOrderBooksToJSON(json: any): ReqGetOrderBooks {
    return ReqGetOrderBooksToJSONTyped(json, false);
}

export function ReqGetOrderBooksToJSONTyped(value?: ReqGetOrderBooks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_id': value['marketId'],
    };
}

