/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetBlockTxs
 */
export interface ReqGetBlockTxs {
    /**
     * 
     * @type {string}
     * @memberof ReqGetBlockTxs
     */
    by: ReqGetBlockTxsByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetBlockTxs
     */
    value: string;
}


/**
 * @export
 */
export const ReqGetBlockTxsByEnum = {
    blockHeight: 'block_height',
    blockCommitment: 'block_commitment'
} as const;
export type ReqGetBlockTxsByEnum = typeof ReqGetBlockTxsByEnum[keyof typeof ReqGetBlockTxsByEnum];


/**
 * Check if a given object implements the ReqGetBlockTxs interface.
 */
export function instanceOfReqGetBlockTxs(value: object): value is ReqGetBlockTxs {
    if (!('by' in value) || value['by'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ReqGetBlockTxsFromJSON(json: any): ReqGetBlockTxs {
    return ReqGetBlockTxsFromJSONTyped(json, false);
}

export function ReqGetBlockTxsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetBlockTxs {
    if (json == null) {
        return json;
    }
    return {
        
        'by': json['by'],
        'value': json['value'],
    };
}

export function ReqGetBlockTxsToJSON(json: any): ReqGetBlockTxs {
    return ReqGetBlockTxsToJSONTyped(json, false);
}

export function ReqGetBlockTxsToJSONTyped(value?: ReqGetBlockTxs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by': value['by'],
        'value': value['value'],
    };
}

