/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetTrades
 */
export interface ReqGetTrades {
    /**
     * 
     * @type {number}
     * @memberof ReqGetTrades
     */
    marketId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetTrades
     */
    accountIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetTrades
     */
    orderIndex?: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetTrades
     */
    sortBy: ReqGetTradesSortByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetTrades
     */
    sortDir?: ReqGetTradesSortDirEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetTrades
     */
    cursor?: string;
    /**
     * 
     * @type {number}
     * @memberof ReqGetTrades
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetTrades
     */
    askFilter?: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetTrades
     */
    limit: number;
}


/**
 * @export
 */
export const ReqGetTradesSortByEnum = {
    blockHeight: 'block_height',
    timestamp: 'timestamp',
    tradeId: 'trade_id'
} as const;
export type ReqGetTradesSortByEnum = typeof ReqGetTradesSortByEnum[keyof typeof ReqGetTradesSortByEnum];

/**
 * @export
 */
export const ReqGetTradesSortDirEnum = {
    asc: 'asc',
    desc: 'desc'
} as const;
export type ReqGetTradesSortDirEnum = typeof ReqGetTradesSortDirEnum[keyof typeof ReqGetTradesSortDirEnum];


/**
 * Check if a given object implements the ReqGetTrades interface.
 */
export function instanceOfReqGetTrades(value: object): value is ReqGetTrades {
    if (!('sortBy' in value) || value['sortBy'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ReqGetTradesFromJSON(json: any): ReqGetTrades {
    return ReqGetTradesFromJSONTyped(json, false);
}

export function ReqGetTradesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetTrades {
    if (json == null) {
        return json;
    }
    return {
        
        'marketId': json['market_id'] == null ? undefined : json['market_id'],
        'accountIndex': json['account_index'] == null ? undefined : json['account_index'],
        'orderIndex': json['order_index'] == null ? undefined : json['order_index'],
        'sortBy': json['sort_by'],
        'sortDir': json['sort_dir'] == null ? undefined : json['sort_dir'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'from': json['from'] == null ? undefined : json['from'],
        'askFilter': json['ask_filter'] == null ? undefined : json['ask_filter'],
        'limit': json['limit'],
    };
}

export function ReqGetTradesToJSON(json: any): ReqGetTrades {
    return ReqGetTradesToJSONTyped(json, false);
}

export function ReqGetTradesToJSONTyped(value?: ReqGetTrades | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_id': value['marketId'],
        'account_index': value['accountIndex'],
        'order_index': value['orderIndex'],
        'sort_by': value['sortBy'],
        'sort_dir': value['sortDir'],
        'cursor': value['cursor'],
        'from': value['from'],
        'ask_filter': value['askFilter'],
        'limit': value['limit'],
    };
}

