/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetAccountActiveOrders
 */
export interface ReqGetAccountActiveOrders {
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountActiveOrders
     */
    accountIndex: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountActiveOrders
     */
    marketId: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountActiveOrders
     */
    auth: string;
}

/**
 * Check if a given object implements the ReqGetAccountActiveOrders interface.
 */
export function instanceOfReqGetAccountActiveOrders(value: object): value is ReqGetAccountActiveOrders {
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    if (!('marketId' in value) || value['marketId'] === undefined) return false;
    if (!('auth' in value) || value['auth'] === undefined) return false;
    return true;
}

export function ReqGetAccountActiveOrdersFromJSON(json: any): ReqGetAccountActiveOrders {
    return ReqGetAccountActiveOrdersFromJSONTyped(json, false);
}

export function ReqGetAccountActiveOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAccountActiveOrders {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIndex': json['account_index'],
        'marketId': json['market_id'],
        'auth': json['auth'],
    };
}

export function ReqGetAccountActiveOrdersToJSON(json: any): ReqGetAccountActiveOrders {
    return ReqGetAccountActiveOrdersToJSONTyped(json, false);
}

export function ReqGetAccountActiveOrdersToJSONTyped(value?: ReqGetAccountActiveOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_index': value['accountIndex'],
        'market_id': value['marketId'],
        'auth': value['auth'],
    };
}

