/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetRecentTrades
 */
export interface ReqGetRecentTrades {
    /**
     * 
     * @type {number}
     * @memberof ReqGetRecentTrades
     */
    marketId: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetRecentTrades
     */
    limit: number;
}

/**
 * Check if a given object implements the ReqGetRecentTrades interface.
 */
export function instanceOfReqGetRecentTrades(value: object): value is ReqGetRecentTrades {
    if (!('marketId' in value) || value['marketId'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ReqGetRecentTradesFromJSON(json: any): ReqGetRecentTrades {
    return ReqGetRecentTradesFromJSONTyped(json, false);
}

export function ReqGetRecentTradesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetRecentTrades {
    if (json == null) {
        return json;
    }
    return {
        
        'marketId': json['market_id'],
        'limit': json['limit'],
    };
}

export function ReqGetRecentTradesToJSON(json: any): ReqGetRecentTrades {
    return ReqGetRecentTradesToJSONTyped(json, false);
}

export function ReqGetRecentTradesToJSONTyped(value?: ReqGetRecentTrades | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_id': value['marketId'],
        'limit': value['limit'],
    };
}

