/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetAccountInactiveOrders
 */
export interface ReqGetAccountInactiveOrders {
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountInactiveOrders
     */
    accountIndex: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountInactiveOrders
     */
    marketId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountInactiveOrders
     */
    askFilter?: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountInactiveOrders
     */
    betweenTimestamps?: string;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountInactiveOrders
     */
    cursor?: string;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountInactiveOrders
     */
    limit: number;
}

/**
 * Check if a given object implements the ReqGetAccountInactiveOrders interface.
 */
export function instanceOfReqGetAccountInactiveOrders(value: object): value is ReqGetAccountInactiveOrders {
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ReqGetAccountInactiveOrdersFromJSON(json: any): ReqGetAccountInactiveOrders {
    return ReqGetAccountInactiveOrdersFromJSONTyped(json, false);
}

export function ReqGetAccountInactiveOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAccountInactiveOrders {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIndex': json['account_index'],
        'marketId': json['market_id'] == null ? undefined : json['market_id'],
        'askFilter': json['ask_filter'] == null ? undefined : json['ask_filter'],
        'betweenTimestamps': json['between_timestamps'] == null ? undefined : json['between_timestamps'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'limit': json['limit'],
    };
}

export function ReqGetAccountInactiveOrdersToJSON(json: any): ReqGetAccountInactiveOrders {
    return ReqGetAccountInactiveOrdersToJSONTyped(json, false);
}

export function ReqGetAccountInactiveOrdersToJSONTyped(value?: ReqGetAccountInactiveOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_index': value['accountIndex'],
        'market_id': value['marketId'],
        'ask_filter': value['askFilter'],
        'between_timestamps': value['betweenTimestamps'],
        'cursor': value['cursor'],
        'limit': value['limit'],
    };
}

