/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetBlock
 */
export interface ReqGetBlock {
    /**
     * 
     * @type {string}
     * @memberof ReqGetBlock
     */
    by: ReqGetBlockByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetBlock
     */
    value: string;
}


/**
 * @export
 */
export const ReqGetBlockByEnum = {
    commitment: 'commitment',
    height: 'height'
} as const;
export type ReqGetBlockByEnum = typeof ReqGetBlockByEnum[keyof typeof ReqGetBlockByEnum];


/**
 * Check if a given object implements the ReqGetBlock interface.
 */
export function instanceOfReqGetBlock(value: object): value is ReqGetBlock {
    if (!('by' in value) || value['by'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ReqGetBlockFromJSON(json: any): ReqGetBlock {
    return ReqGetBlockFromJSONTyped(json, false);
}

export function ReqGetBlockFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetBlock {
    if (json == null) {
        return json;
    }
    return {
        
        'by': json['by'],
        'value': json['value'],
    };
}

export function ReqGetBlockToJSON(json: any): ReqGetBlock {
    return ReqGetBlockToJSONTyped(json, false);
}

export function ReqGetBlockToJSONTyped(value?: ReqGetBlock | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by': value['by'],
        'value': value['value'],
    };
}

