/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetFeeBucket
 */
export interface ReqGetFeeBucket {
    /**
     * 
     * @type {number}
     * @memberof ReqGetFeeBucket
     */
    accountIndex: number;
}

/**
 * Check if a given object implements the ReqGetFeeBucket interface.
 */
export function instanceOfReqGetFeeBucket(value: object): value is ReqGetFeeBucket {
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    return true;
}

export function ReqGetFeeBucketFromJSON(json: any): ReqGetFeeBucket {
    return ReqGetFeeBucketFromJSONTyped(json, false);
}

export function ReqGetFeeBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetFeeBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIndex': json['account_index'],
    };
}

export function ReqGetFeeBucketToJSON(json: any): ReqGetFeeBucket {
    return ReqGetFeeBucketToJSONTyped(json, false);
}

export function ReqGetFeeBucketToJSONTyped(value?: ReqGetFeeBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_index': value['accountIndex'],
    };
}

