/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetAccount
 */
export interface ReqGetAccount {
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccount
     */
    by: ReqGetAccountByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccount
     */
    value: string;
}


/**
 * @export
 */
export const ReqGetAccountByEnum = {
    index: 'index',
    l1Address: 'l1_address'
} as const;
export type ReqGetAccountByEnum = typeof ReqGetAccountByEnum[keyof typeof ReqGetAccountByEnum];


/**
 * Check if a given object implements the ReqGetAccount interface.
 */
export function instanceOfReqGetAccount(value: object): value is ReqGetAccount {
    if (!('by' in value) || value['by'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function ReqGetAccountFromJSON(json: any): ReqGetAccount {
    return ReqGetAccountFromJSONTyped(json, false);
}

export function ReqGetAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'by': json['by'],
        'value': json['value'],
    };
}

export function ReqGetAccountToJSON(json: any): ReqGetAccount {
    return ReqGetAccountToJSONTyped(json, false);
}

export function ReqGetAccountToJSONTyped(value?: ReqGetAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by': value['by'],
        'value': value['value'],
    };
}

