/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetFundings
 */
export interface ReqGetFundings {
    /**
     * 
     * @type {number}
     * @memberof ReqGetFundings
     */
    marketId: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetFundings
     */
    resolution: ReqGetFundingsResolutionEnum;
    /**
     * 
     * @type {number}
     * @memberof ReqGetFundings
     */
    startTimestamp: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetFundings
     */
    endTimestamp: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetFundings
     */
    countBack: number;
}


/**
 * @export
 */
export const ReqGetFundingsResolutionEnum = {
    _1h: '1h'
} as const;
export type ReqGetFundingsResolutionEnum = typeof ReqGetFundingsResolutionEnum[keyof typeof ReqGetFundingsResolutionEnum];


/**
 * Check if a given object implements the ReqGetFundings interface.
 */
export function instanceOfReqGetFundings(value: object): value is ReqGetFundings {
    if (!('marketId' in value) || value['marketId'] === undefined) return false;
    if (!('resolution' in value) || value['resolution'] === undefined) return false;
    if (!('startTimestamp' in value) || value['startTimestamp'] === undefined) return false;
    if (!('endTimestamp' in value) || value['endTimestamp'] === undefined) return false;
    if (!('countBack' in value) || value['countBack'] === undefined) return false;
    return true;
}

export function ReqGetFundingsFromJSON(json: any): ReqGetFundings {
    return ReqGetFundingsFromJSONTyped(json, false);
}

export function ReqGetFundingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetFundings {
    if (json == null) {
        return json;
    }
    return {
        
        'marketId': json['market_id'],
        'resolution': json['resolution'],
        'startTimestamp': json['start_timestamp'],
        'endTimestamp': json['end_timestamp'],
        'countBack': json['count_back'],
    };
}

export function ReqGetFundingsToJSON(json: any): ReqGetFundings {
    return ReqGetFundingsToJSONTyped(json, false);
}

export function ReqGetFundingsToJSONTyped(value?: ReqGetFundings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_id': value['marketId'],
        'resolution': value['resolution'],
        'start_timestamp': value['startTimestamp'],
        'end_timestamp': value['endTimestamp'],
        'count_back': value['countBack'],
    };
}

