/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqIsWhitelisted
 */
export interface ReqIsWhitelisted {
    /**
     * 
     * @type {string}
     * @memberof ReqIsWhitelisted
     */
    l1Address: string;
}

/**
 * Check if a given object implements the ReqIsWhitelisted interface.
 */
export function instanceOfReqIsWhitelisted(value: object): value is ReqIsWhitelisted {
    if (!('l1Address' in value) || value['l1Address'] === undefined) return false;
    return true;
}

export function ReqIsWhitelistedFromJSON(json: any): ReqIsWhitelisted {
    return ReqIsWhitelistedFromJSONTyped(json, false);
}

export function ReqIsWhitelistedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqIsWhitelisted {
    if (json == null) {
        return json;
    }
    return {
        
        'l1Address': json['l1_address'],
    };
}

export function ReqIsWhitelistedToJSON(json: any): ReqIsWhitelisted {
    return ReqIsWhitelistedToJSONTyped(json, false);
}

export function ReqIsWhitelistedToJSONTyped(value?: ReqIsWhitelisted | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'l1_address': value['l1Address'],
    };
}

