/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultCode
 */
export interface ResultCode {
    /**
     * 
     * @type {number}
     * @memberof ResultCode
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof ResultCode
     */
    message?: string;
}

/**
 * Check if a given object implements the ResultCode interface.
 */
export function instanceOfResultCode(value: object): value is ResultCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ResultCodeFromJSON(json: any): ResultCode {
    return ResultCodeFromJSONTyped(json, false);
}

export function ResultCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ResultCodeToJSON(json: any): ResultCode {
    return ResultCodeToJSONTyped(json, false);
}

export function ResultCodeToJSONTyped(value?: ResultCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

