/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleOrder
 */
export interface SimpleOrder {
    /**
     * 
     * @type {number}
     * @memberof SimpleOrder
     */
    orderIndex: number;
    /**
     * 
     * @type {number}
     * @memberof SimpleOrder
     */
    ownerAccountIndex: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleOrder
     */
    initialBaseAmount: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleOrder
     */
    remainingBaseAmount: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleOrder
     */
    price: string;
    /**
     * 
     * @type {number}
     * @memberof SimpleOrder
     */
    orderExpiry: number;
}

/**
 * Check if a given object implements the SimpleOrder interface.
 */
export function instanceOfSimpleOrder(value: object): value is SimpleOrder {
    if (!('orderIndex' in value) || value['orderIndex'] === undefined) return false;
    if (!('ownerAccountIndex' in value) || value['ownerAccountIndex'] === undefined) return false;
    if (!('initialBaseAmount' in value) || value['initialBaseAmount'] === undefined) return false;
    if (!('remainingBaseAmount' in value) || value['remainingBaseAmount'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('orderExpiry' in value) || value['orderExpiry'] === undefined) return false;
    return true;
}

export function SimpleOrderFromJSON(json: any): SimpleOrder {
    return SimpleOrderFromJSONTyped(json, false);
}

export function SimpleOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'orderIndex': json['order_index'],
        'ownerAccountIndex': json['owner_account_index'],
        'initialBaseAmount': json['initial_base_amount'],
        'remainingBaseAmount': json['remaining_base_amount'],
        'price': json['price'],
        'orderExpiry': json['order_expiry'],
    };
}

export function SimpleOrderToJSON(json: any): SimpleOrder {
    return SimpleOrderToJSONTyped(json, false);
}

export function SimpleOrderToJSONTyped(value?: SimpleOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_index': value['orderIndex'],
        'owner_account_index': value['ownerAccountIndex'],
        'initial_base_amount': value['initialBaseAmount'],
        'remaining_base_amount': value['remainingBaseAmount'],
        'price': value['price'],
        'order_expiry': value['orderExpiry'],
    };
}

