/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';

/**
 * 
 * @export
 * @interface SubAccounts
 */
export interface SubAccounts {
    /**
     * 
     * @type {number}
     * @memberof SubAccounts
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof SubAccounts
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SubAccounts
     */
    l1Address: string;
    /**
     * 
     * @type {Array<Account>}
     * @memberof SubAccounts
     */
    subAccounts: Array<Account>;
}

/**
 * Check if a given object implements the SubAccounts interface.
 */
export function instanceOfSubAccounts(value: object): value is SubAccounts {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('l1Address' in value) || value['l1Address'] === undefined) return false;
    if (!('subAccounts' in value) || value['subAccounts'] === undefined) return false;
    return true;
}

export function SubAccountsFromJSON(json: any): SubAccounts {
    return SubAccountsFromJSONTyped(json, false);
}

export function SubAccountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubAccounts {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'l1Address': json['l1_address'],
        'subAccounts': ((json['sub_accounts'] as Array<any>).map(AccountFromJSON)),
    };
}

export function SubAccountsToJSON(json: any): SubAccounts {
    return SubAccountsToJSONTyped(json, false);
}

export function SubAccountsToJSONTyped(value?: SubAccounts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'l1_address': value['l1Address'],
        'sub_accounts': ((value['subAccounts'] as Array<any>).map(AccountToJSON)),
    };
}

