/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidatorInfo
 */
export interface ValidatorInfo {
    /**
     * 
     * @type {string}
     * @memberof ValidatorInfo
     */
    address: string;
    /**
     * 
     * @type {boolean}
     * @memberof ValidatorInfo
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the ValidatorInfo interface.
 */
export function instanceOfValidatorInfo(value: object): value is ValidatorInfo {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function ValidatorInfoFromJSON(json: any): ValidatorInfo {
    return ValidatorInfoFromJSONTyped(json, false);
}

export function ValidatorInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatorInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'isActive': json['is_active'],
    };
}

export function ValidatorInfoToJSON(json: any): ValidatorInfo {
    return ValidatorInfoToJSONTyped(json, false);
}

export function ValidatorInfoToJSONTyped(value?: ValidatorInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'is_active': value['isActive'],
    };
}

