/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ZkLighterInfo
 */
export interface ZkLighterInfo {
    /**
     * 
     * @type {string}
     * @memberof ZkLighterInfo
     */
    contractAddress: string;
}

/**
 * Check if a given object implements the ZkLighterInfo interface.
 */
export function instanceOfZkLighterInfo(value: object): value is ZkLighterInfo {
    if (!('contractAddress' in value) || value['contractAddress'] === undefined) return false;
    return true;
}

export function ZkLighterInfoFromJSON(json: any): ZkLighterInfo {
    return ZkLighterInfoFromJSONTyped(json, false);
}

export function ZkLighterInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZkLighterInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'contractAddress': json['contract_address'],
    };
}

export function ZkLighterInfoToJSON(json: any): ZkLighterInfo {
    return ZkLighterInfoToJSONTyped(json, false);
}

export function ZkLighterInfoToJSONTyped(value?: ZkLighterInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contract_address': value['contractAddress'],
    };
}

