/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountMarketStats
 */
export interface AccountMarketStats {
    /**
     * 
     * @type {number}
     * @memberof AccountMarketStats
     */
    marketId: number;
    /**
     * 
     * @type {number}
     * @memberof AccountMarketStats
     */
    dailyTradesCount: number;
    /**
     * 
     * @type {number}
     * @memberof AccountMarketStats
     */
    dailyBaseTokenVolume: number;
    /**
     * 
     * @type {number}
     * @memberof AccountMarketStats
     */
    dailyQuoteTokenVolume: number;
}

/**
 * Check if a given object implements the AccountMarketStats interface.
 */
export function instanceOfAccountMarketStats(value: object): value is AccountMarketStats {
    if (!('marketId' in value) || value['marketId'] === undefined) return false;
    if (!('dailyTradesCount' in value) || value['dailyTradesCount'] === undefined) return false;
    if (!('dailyBaseTokenVolume' in value) || value['dailyBaseTokenVolume'] === undefined) return false;
    if (!('dailyQuoteTokenVolume' in value) || value['dailyQuoteTokenVolume'] === undefined) return false;
    return true;
}

export function AccountMarketStatsFromJSON(json: any): AccountMarketStats {
    return AccountMarketStatsFromJSONTyped(json, false);
}

export function AccountMarketStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountMarketStats {
    if (json == null) {
        return json;
    }
    return {
        
        'marketId': json['market_id'],
        'dailyTradesCount': json['daily_trades_count'],
        'dailyBaseTokenVolume': json['daily_base_token_volume'],
        'dailyQuoteTokenVolume': json['daily_quote_token_volume'],
    };
}

export function AccountMarketStatsToJSON(json: any): AccountMarketStats {
    return AccountMarketStatsToJSONTyped(json, false);
}

export function AccountMarketStatsToJSONTyped(value?: AccountMarketStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_id': value['marketId'],
        'daily_trades_count': value['dailyTradesCount'],
        'daily_base_token_volume': value['dailyBaseTokenVolume'],
        'daily_quote_token_volume': value['dailyQuoteTokenVolume'],
    };
}

