/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    accountType: number;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    l1Address: string;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    cancelAllTime: number;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    totalOrderCount: number;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    pendingOrderCount: number;
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    collateral: string;
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('l1Address' in value) || value['l1Address'] === undefined) return false;
    if (!('cancelAllTime' in value) || value['cancelAllTime'] === undefined) return false;
    if (!('totalOrderCount' in value) || value['totalOrderCount'] === undefined) return false;
    if (!('pendingOrderCount' in value) || value['pendingOrderCount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('collateral' in value) || value['collateral'] === undefined) return false;
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'accountType': json['account_type'],
        'index': json['index'],
        'l1Address': json['l1_address'],
        'cancelAllTime': json['cancel_all_time'],
        'totalOrderCount': json['total_order_count'],
        'pendingOrderCount': json['pending_order_count'],
        'status': json['status'],
        'collateral': json['collateral'],
    };
}

export function AccountToJSON(json: any): Account {
    return AccountToJSONTyped(json, false);
}

export function AccountToJSONTyped(value?: Account | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'account_type': value['accountType'],
        'index': value['index'],
        'l1_address': value['l1Address'],
        'cancel_all_time': value['cancelAllTime'],
        'total_order_count': value['totalOrderCount'],
        'pending_order_count': value['pendingOrderCount'],
        'status': value['status'],
        'collateral': value['collateral'],
    };
}

