/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKey
 */
export interface ApiKey {
    /**
     * 
     * @type {number}
     * @memberof ApiKey
     */
    accountIndex: number;
    /**
     * 
     * @type {number}
     * @memberof ApiKey
     */
    apiKeyIndex: number;
    /**
     * 
     * @type {number}
     * @memberof ApiKey
     */
    nonce: number;
    /**
     * 
     * @type {string}
     * @memberof ApiKey
     */
    publicKey: string;
}

/**
 * Check if a given object implements the ApiKey interface.
 */
export function instanceOfApiKey(value: object): value is ApiKey {
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    if (!('apiKeyIndex' in value) || value['apiKeyIndex'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('publicKey' in value) || value['publicKey'] === undefined) return false;
    return true;
}

export function ApiKeyFromJSON(json: any): ApiKey {
    return ApiKeyFromJSONTyped(json, false);
}

export function ApiKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKey {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIndex': json['account_index'],
        'apiKeyIndex': json['api_key_index'],
        'nonce': json['nonce'],
        'publicKey': json['public_key'],
    };
}

export function ApiKeyToJSON(json: any): ApiKey {
    return ApiKeyToJSONTyped(json, false);
}

export function ApiKeyToJSONTyped(value?: ApiKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_index': value['accountIndex'],
        'api_key_index': value['apiKeyIndex'],
        'nonce': value['nonce'],
        'public_key': value['publicKey'],
    };
}

