/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Candlestick
 */
export interface Candlestick {
    /**
     * 
     * @type {number}
     * @memberof Candlestick
     */
    timestamp: number;
    /**
     * 
     * @type {number}
     * @memberof Candlestick
     */
    open: number;
    /**
     * 
     * @type {number}
     * @memberof Candlestick
     */
    high: number;
    /**
     * 
     * @type {number}
     * @memberof Candlestick
     */
    low: number;
    /**
     * 
     * @type {number}
     * @memberof Candlestick
     */
    close: number;
    /**
     * 
     * @type {number}
     * @memberof Candlestick
     */
    volume0: number;
    /**
     * 
     * @type {number}
     * @memberof Candlestick
     */
    volume1: number;
    /**
     * 
     * @type {number}
     * @memberof Candlestick
     */
    lastTradeId: number;
}

/**
 * Check if a given object implements the Candlestick interface.
 */
export function instanceOfCandlestick(value: object): value is Candlestick {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('open' in value) || value['open'] === undefined) return false;
    if (!('high' in value) || value['high'] === undefined) return false;
    if (!('low' in value) || value['low'] === undefined) return false;
    if (!('close' in value) || value['close'] === undefined) return false;
    if (!('volume0' in value) || value['volume0'] === undefined) return false;
    if (!('volume1' in value) || value['volume1'] === undefined) return false;
    if (!('lastTradeId' in value) || value['lastTradeId'] === undefined) return false;
    return true;
}

export function CandlestickFromJSON(json: any): Candlestick {
    return CandlestickFromJSONTyped(json, false);
}

export function CandlestickFromJSONTyped(json: any, ignoreDiscriminator: boolean): Candlestick {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'open': json['open'],
        'high': json['high'],
        'low': json['low'],
        'close': json['close'],
        'volume0': json['volume0'],
        'volume1': json['volume1'],
        'lastTradeId': json['last_trade_id'],
    };
}

export function CandlestickToJSON(json: any): Candlestick {
    return CandlestickToJSONTyped(json, false);
}

export function CandlestickToJSONTyped(value?: Candlestick | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'open': value['open'],
        'high': value['high'],
        'low': value['low'],
        'close': value['close'],
        'volume0': value['volume0'],
        'volume1': value['volume1'],
        'last_trade_id': value['lastTradeId'],
    };
}

