/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractAddress
 */
export interface ContractAddress {
    /**
     * 
     * @type {string}
     * @memberof ContractAddress
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddress
     */
    address: string;
}

/**
 * Check if a given object implements the ContractAddress interface.
 */
export function instanceOfContractAddress(value: object): value is ContractAddress {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function ContractAddressFromJSON(json: any): ContractAddress {
    return ContractAddressFromJSONTyped(json, false);
}

export function ContractAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': json['address'],
    };
}

export function ContractAddressToJSON(json: any): ContractAddress {
    return ContractAddressToJSONTyped(json, false);
}

export function ContractAddressToJSONTyped(value?: ContractAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'address': value['address'],
    };
}

