/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentHeight
 */
export interface CurrentHeight {
    /**
     * 
     * @type {number}
     * @memberof CurrentHeight
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof CurrentHeight
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof CurrentHeight
     */
    height: number;
}

/**
 * Check if a given object implements the CurrentHeight interface.
 */
export function instanceOfCurrentHeight(value: object): value is CurrentHeight {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    return true;
}

export function CurrentHeightFromJSON(json: any): CurrentHeight {
    return CurrentHeightFromJSONTyped(json, false);
}

export function CurrentHeightFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentHeight {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'height': json['height'],
    };
}

export function CurrentHeightToJSON(json: any): CurrentHeight {
    return CurrentHeightToJSONTyped(json, false);
}

export function CurrentHeightToJSONTyped(value?: CurrentHeight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'height': value['height'],
    };
}

