/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DepositHistoryItem } from './DepositHistoryItem';
import {
    DepositHistoryItemFromJSON,
    DepositHistoryItemFromJSONTyped,
    DepositHistoryItemToJSON,
    DepositHistoryItemToJSONTyped,
} from './DepositHistoryItem';

/**
 * 
 * @export
 * @interface DepositHistory
 */
export interface DepositHistory {
    /**
     * 
     * @type {number}
     * @memberof DepositHistory
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof DepositHistory
     */
    message?: string;
    /**
     * 
     * @type {Array<DepositHistoryItem>}
     * @memberof DepositHistory
     */
    deposits: Array<DepositHistoryItem>;
    /**
     * 
     * @type {string}
     * @memberof DepositHistory
     */
    cursor: string;
}

/**
 * Check if a given object implements the DepositHistory interface.
 */
export function instanceOfDepositHistory(value: object): value is DepositHistory {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('deposits' in value) || value['deposits'] === undefined) return false;
    if (!('cursor' in value) || value['cursor'] === undefined) return false;
    return true;
}

export function DepositHistoryFromJSON(json: any): DepositHistory {
    return DepositHistoryFromJSONTyped(json, false);
}

export function DepositHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepositHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'deposits': ((json['deposits'] as Array<any>).map(DepositHistoryItemFromJSON)),
        'cursor': json['cursor'],
    };
}

export function DepositHistoryToJSON(json: any): DepositHistory {
    return DepositHistoryToJSONTyped(json, false);
}

export function DepositHistoryToJSONTyped(value?: DepositHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'deposits': ((value['deposits'] as Array<any>).map(DepositHistoryItemToJSON)),
        'cursor': value['cursor'],
    };
}

