/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountMarketStats } from './AccountMarketStats';
import {
    AccountMarketStatsFromJSON,
    AccountMarketStatsFromJSONTyped,
    AccountMarketStatsToJSON,
    AccountMarketStatsToJSONTyped,
} from './AccountMarketStats';
import type { AccountPosition } from './AccountPosition';
import {
    AccountPositionFromJSON,
    AccountPositionFromJSONTyped,
    AccountPositionToJSON,
    AccountPositionToJSONTyped,
} from './AccountPosition';
import type { PublicPoolInfo } from './PublicPoolInfo';
import {
    PublicPoolInfoFromJSON,
    PublicPoolInfoFromJSONTyped,
    PublicPoolInfoToJSON,
    PublicPoolInfoToJSONTyped,
} from './PublicPoolInfo';
import type { PublicPoolShare } from './PublicPoolShare';
import {
    PublicPoolShareFromJSON,
    PublicPoolShareFromJSONTyped,
    PublicPoolShareToJSON,
    PublicPoolShareToJSONTyped,
} from './PublicPoolShare';

/**
 * 
 * @export
 * @interface DetailedAccount
 */
export interface DetailedAccount {
    /**
     * 
     * @type {number}
     * @memberof DetailedAccount
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof DetailedAccount
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof DetailedAccount
     */
    accountType: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedAccount
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof DetailedAccount
     */
    l1Address: string;
    /**
     * 
     * @type {number}
     * @memberof DetailedAccount
     */
    cancelAllTime: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedAccount
     */
    totalOrderCount: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedAccount
     */
    pendingOrderCount: number;
    /**
     * 
     * @type {number}
     * @memberof DetailedAccount
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof DetailedAccount
     */
    collateral: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedAccount
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DetailedAccount
     */
    description: string;
    /**
     * 
     * @type {Array<AccountPosition>}
     * @memberof DetailedAccount
     */
    positions: Array<AccountPosition>;
    /**
     * 
     * @type {string}
     * @memberof DetailedAccount
     */
    totalAssetValue: string;
    /**
     * 
     * @type {Array<AccountMarketStats>}
     * @memberof DetailedAccount
     */
    marketStats: Array<AccountMarketStats>;
    /**
     * 
     * @type {PublicPoolInfo}
     * @memberof DetailedAccount
     */
    poolInfo: PublicPoolInfo;
    /**
     * 
     * @type {Array<PublicPoolShare>}
     * @memberof DetailedAccount
     */
    shares: Array<PublicPoolShare>;
}

/**
 * Check if a given object implements the DetailedAccount interface.
 */
export function instanceOfDetailedAccount(value: object): value is DetailedAccount {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('l1Address' in value) || value['l1Address'] === undefined) return false;
    if (!('cancelAllTime' in value) || value['cancelAllTime'] === undefined) return false;
    if (!('totalOrderCount' in value) || value['totalOrderCount'] === undefined) return false;
    if (!('pendingOrderCount' in value) || value['pendingOrderCount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('collateral' in value) || value['collateral'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('positions' in value) || value['positions'] === undefined) return false;
    if (!('totalAssetValue' in value) || value['totalAssetValue'] === undefined) return false;
    if (!('marketStats' in value) || value['marketStats'] === undefined) return false;
    if (!('poolInfo' in value) || value['poolInfo'] === undefined) return false;
    if (!('shares' in value) || value['shares'] === undefined) return false;
    return true;
}

export function DetailedAccountFromJSON(json: any): DetailedAccount {
    return DetailedAccountFromJSONTyped(json, false);
}

export function DetailedAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailedAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'accountType': json['account_type'],
        'index': json['index'],
        'l1Address': json['l1_address'],
        'cancelAllTime': json['cancel_all_time'],
        'totalOrderCount': json['total_order_count'],
        'pendingOrderCount': json['pending_order_count'],
        'status': json['status'],
        'collateral': json['collateral'],
        'name': json['name'],
        'description': json['description'],
        'positions': ((json['positions'] as Array<any>).map(AccountPositionFromJSON)),
        'totalAssetValue': json['total_asset_value'],
        'marketStats': ((json['market_stats'] as Array<any>).map(AccountMarketStatsFromJSON)),
        'poolInfo': PublicPoolInfoFromJSON(json['pool_info']),
        'shares': ((json['shares'] as Array<any>).map(PublicPoolShareFromJSON)),
    };
}

export function DetailedAccountToJSON(json: any): DetailedAccount {
    return DetailedAccountToJSONTyped(json, false);
}

export function DetailedAccountToJSONTyped(value?: DetailedAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'account_type': value['accountType'],
        'index': value['index'],
        'l1_address': value['l1Address'],
        'cancel_all_time': value['cancelAllTime'],
        'total_order_count': value['totalOrderCount'],
        'pending_order_count': value['pendingOrderCount'],
        'status': value['status'],
        'collateral': value['collateral'],
        'name': value['name'],
        'description': value['description'],
        'positions': ((value['positions'] as Array<any>).map(AccountPositionToJSON)),
        'total_asset_value': value['totalAssetValue'],
        'market_stats': ((value['marketStats'] as Array<any>).map(AccountMarketStatsToJSON)),
        'pool_info': PublicPoolInfoToJSON(value['poolInfo']),
        'shares': ((value['shares'] as Array<any>).map(PublicPoolShareToJSON)),
    };
}

