/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnrichedTx
 */
export interface EnrichedTx {
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof EnrichedTx
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof EnrichedTx
     */
    hash: string;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    type: number;
    /**
     * 
     * @type {string}
     * @memberof EnrichedTx
     */
    info: string;
    /**
     * 
     * @type {string}
     * @memberof EnrichedTx
     */
    eventInfo: string;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    status: number;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    transactionIndex: number;
    /**
     * 
     * @type {string}
     * @memberof EnrichedTx
     */
    l1Address: string;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    accountIndex: number;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    nonce: number;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    expireAt: number;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    blockHeight: number;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    queuedAt: number;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    executedAt: number;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    sequenceIndex: number;
    /**
     * 
     * @type {string}
     * @memberof EnrichedTx
     */
    parentHash: string;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    committedAt: number;
    /**
     * 
     * @type {number}
     * @memberof EnrichedTx
     */
    verifiedAt: number;
}

/**
 * Check if a given object implements the EnrichedTx interface.
 */
export function instanceOfEnrichedTx(value: object): value is EnrichedTx {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('info' in value) || value['info'] === undefined) return false;
    if (!('eventInfo' in value) || value['eventInfo'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('transactionIndex' in value) || value['transactionIndex'] === undefined) return false;
    if (!('l1Address' in value) || value['l1Address'] === undefined) return false;
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('expireAt' in value) || value['expireAt'] === undefined) return false;
    if (!('blockHeight' in value) || value['blockHeight'] === undefined) return false;
    if (!('queuedAt' in value) || value['queuedAt'] === undefined) return false;
    if (!('executedAt' in value) || value['executedAt'] === undefined) return false;
    if (!('sequenceIndex' in value) || value['sequenceIndex'] === undefined) return false;
    if (!('parentHash' in value) || value['parentHash'] === undefined) return false;
    if (!('committedAt' in value) || value['committedAt'] === undefined) return false;
    if (!('verifiedAt' in value) || value['verifiedAt'] === undefined) return false;
    return true;
}

export function EnrichedTxFromJSON(json: any): EnrichedTx {
    return EnrichedTxFromJSONTyped(json, false);
}

export function EnrichedTxFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichedTx {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'hash': json['hash'],
        'type': json['type'],
        'info': json['info'],
        'eventInfo': json['event_info'],
        'status': json['status'],
        'transactionIndex': json['transaction_index'],
        'l1Address': json['l1_address'],
        'accountIndex': json['account_index'],
        'nonce': json['nonce'],
        'expireAt': json['expire_at'],
        'blockHeight': json['block_height'],
        'queuedAt': json['queued_at'],
        'executedAt': json['executed_at'],
        'sequenceIndex': json['sequence_index'],
        'parentHash': json['parent_hash'],
        'committedAt': json['committed_at'],
        'verifiedAt': json['verified_at'],
    };
}

export function EnrichedTxToJSON(json: any): EnrichedTx {
    return EnrichedTxToJSONTyped(json, false);
}

export function EnrichedTxToJSONTyped(value?: EnrichedTx | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'hash': value['hash'],
        'type': value['type'],
        'info': value['info'],
        'event_info': value['eventInfo'],
        'status': value['status'],
        'transaction_index': value['transactionIndex'],
        'l1_address': value['l1Address'],
        'account_index': value['accountIndex'],
        'nonce': value['nonce'],
        'expire_at': value['expireAt'],
        'block_height': value['blockHeight'],
        'queued_at': value['queuedAt'],
        'executed_at': value['executedAt'],
        'sequence_index': value['sequenceIndex'],
        'parent_hash': value['parentHash'],
        'committed_at': value['committedAt'],
        'verified_at': value['verifiedAt'],
    };
}

