/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Liquidation
 */
export interface Liquidation {
    /**
     * 
     * @type {number}
     * @memberof Liquidation
     */
    liquidationId: number;
    /**
     * 
     * @type {number}
     * @memberof Liquidation
     */
    accountIndex: number;
    /**
     * 
     * @type {number}
     * @memberof Liquidation
     */
    liquidationType: number;
    /**
     * 
     * @type {string}
     * @memberof Liquidation
     */
    portfolioValue: string;
    /**
     * 
     * @type {string}
     * @memberof Liquidation
     */
    marginRequirement: string;
}

/**
 * Check if a given object implements the Liquidation interface.
 */
export function instanceOfLiquidation(value: object): value is Liquidation {
    if (!('liquidationId' in value) || value['liquidationId'] === undefined) return false;
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    if (!('liquidationType' in value) || value['liquidationType'] === undefined) return false;
    if (!('portfolioValue' in value) || value['portfolioValue'] === undefined) return false;
    if (!('marginRequirement' in value) || value['marginRequirement'] === undefined) return false;
    return true;
}

export function LiquidationFromJSON(json: any): Liquidation {
    return LiquidationFromJSONTyped(json, false);
}

export function LiquidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Liquidation {
    if (json == null) {
        return json;
    }
    return {
        
        'liquidationId': json['liquidation_id'],
        'accountIndex': json['account_index'],
        'liquidationType': json['liquidation_type'],
        'portfolioValue': json['portfolio_value'],
        'marginRequirement': json['margin_requirement'],
    };
}

export function LiquidationToJSON(json: any): Liquidation {
    return LiquidationToJSONTyped(json, false);
}

export function LiquidationToJSONTyped(value?: Liquidation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'liquidation_id': value['liquidationId'],
        'account_index': value['accountIndex'],
        'liquidation_type': value['liquidationType'],
        'portfolio_value': value['portfolioValue'],
        'margin_requirement': value['marginRequirement'],
    };
}

