/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceLevel } from './PriceLevel';
import {
    PriceLevelFromJSON,
    PriceLevelFromJSONTyped,
    PriceLevelToJSON,
    PriceLevelToJSONTyped,
} from './PriceLevel';

/**
 * 
 * @export
 * @interface OrderBookDepth
 */
export interface OrderBookDepth {
    /**
     * 
     * @type {number}
     * @memberof OrderBookDepth
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof OrderBookDepth
     */
    message?: string;
    /**
     * 
     * @type {Array<PriceLevel>}
     * @memberof OrderBookDepth
     */
    asks: Array<PriceLevel>;
    /**
     * 
     * @type {Array<PriceLevel>}
     * @memberof OrderBookDepth
     */
    bids: Array<PriceLevel>;
    /**
     * 
     * @type {number}
     * @memberof OrderBookDepth
     */
    offset: number;
}

/**
 * Check if a given object implements the OrderBookDepth interface.
 */
export function instanceOfOrderBookDepth(value: object): value is OrderBookDepth {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('asks' in value) || value['asks'] === undefined) return false;
    if (!('bids' in value) || value['bids'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function OrderBookDepthFromJSON(json: any): OrderBookDepth {
    return OrderBookDepthFromJSONTyped(json, false);
}

export function OrderBookDepthFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBookDepth {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'asks': ((json['asks'] as Array<any>).map(PriceLevelFromJSON)),
        'bids': ((json['bids'] as Array<any>).map(PriceLevelFromJSON)),
        'offset': json['offset'],
    };
}

export function OrderBookDepthToJSON(json: any): OrderBookDepth {
    return OrderBookDepthToJSONTyped(json, false);
}

export function OrderBookDepthToJSONTyped(value?: OrderBookDepth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'asks': ((value['asks'] as Array<any>).map(PriceLevelToJSON)),
        'bids': ((value['bids'] as Array<any>).map(PriceLevelToJSON)),
        'offset': value['offset'],
    };
}

