/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';

/**
 * 
 * @export
 * @interface Orders
 */
export interface Orders {
    /**
     * 
     * @type {number}
     * @memberof Orders
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof Orders
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof Orders
     */
    nextCursor?: string;
    /**
     * 
     * @type {Array<Order>}
     * @memberof Orders
     */
    orders: Array<Order>;
}

/**
 * Check if a given object implements the Orders interface.
 */
export function instanceOfOrders(value: object): value is Orders {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('orders' in value) || value['orders'] === undefined) return false;
    return true;
}

export function OrdersFromJSON(json: any): Orders {
    return OrdersFromJSONTyped(json, false);
}

export function OrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): Orders {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'nextCursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'orders': ((json['orders'] as Array<any>).map(OrderFromJSON)),
    };
}

export function OrdersToJSON(json: any): Orders {
    return OrdersToJSONTyped(json, false);
}

export function OrdersToJSONTyped(value?: Orders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'next_cursor': value['nextCursor'],
        'orders': ((value['orders'] as Array<any>).map(OrderToJSON)),
    };
}

