/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderBook } from './OrderBook';
import {
    OrderBookFromJSON,
    OrderBookFromJSONTyped,
    OrderBookToJSON,
    OrderBookToJSONTyped,
} from './OrderBook';

/**
 * 
 * @export
 * @interface OrderBooks
 */
export interface OrderBooks {
    /**
     * 
     * @type {number}
     * @memberof OrderBooks
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof OrderBooks
     */
    message?: string;
    /**
     * 
     * @type {Array<OrderBook>}
     * @memberof OrderBooks
     */
    orderBooks: Array<OrderBook>;
}

/**
 * Check if a given object implements the OrderBooks interface.
 */
export function instanceOfOrderBooks(value: object): value is OrderBooks {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('orderBooks' in value) || value['orderBooks'] === undefined) return false;
    return true;
}

export function OrderBooksFromJSON(json: any): OrderBooks {
    return OrderBooksFromJSONTyped(json, false);
}

export function OrderBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderBooks {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'orderBooks': ((json['order_books'] as Array<any>).map(OrderBookFromJSON)),
    };
}

export function OrderBooksToJSON(json: any): OrderBooks {
    return OrderBooksToJSONTyped(json, false);
}

export function OrderBooksToJSONTyped(value?: OrderBooks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'order_books': ((value['orderBooks'] as Array<any>).map(OrderBookToJSON)),
    };
}

