/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PnLEntry
 */
export interface PnLEntry {
    /**
     * 
     * @type {number}
     * @memberof PnLEntry
     */
    timestamp: number;
    /**
     * 
     * @type {number}
     * @memberof PnLEntry
     */
    value: number;
}

/**
 * Check if a given object implements the PnLEntry interface.
 */
export function instanceOfPnLEntry(value: object): value is PnLEntry {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function PnLEntryFromJSON(json: any): PnLEntry {
    return PnLEntryFromJSONTyped(json, false);
}

export function PnLEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PnLEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'value': json['value'],
    };
}

export function PnLEntryToJSON(json: any): PnLEntry {
    return PnLEntryToJSONTyped(json, false);
}

export function PnLEntryToJSONTyped(value?: PnLEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'value': value['value'],
    };
}

