/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PositionFunding
 */
export interface PositionFunding {
    /**
     * 
     * @type {number}
     * @memberof PositionFunding
     */
    timestamp: number;
    /**
     * 
     * @type {number}
     * @memberof PositionFunding
     */
    marketId: number;
    /**
     * 
     * @type {number}
     * @memberof PositionFunding
     */
    fundingId: number;
    /**
     * 
     * @type {string}
     * @memberof PositionFunding
     */
    change: string;
    /**
     * 
     * @type {string}
     * @memberof PositionFunding
     */
    rate: string;
    /**
     * 
     * @type {string}
     * @memberof PositionFunding
     */
    positionSize: string;
    /**
     * 
     * @type {string}
     * @memberof PositionFunding
     */
    positionSide: PositionFundingPositionSideEnum;
}


/**
 * @export
 */
export const PositionFundingPositionSideEnum = {
    long: 'long',
    short: 'short'
} as const;
export type PositionFundingPositionSideEnum = typeof PositionFundingPositionSideEnum[keyof typeof PositionFundingPositionSideEnum];


/**
 * Check if a given object implements the PositionFunding interface.
 */
export function instanceOfPositionFunding(value: object): value is PositionFunding {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('marketId' in value) || value['marketId'] === undefined) return false;
    if (!('fundingId' in value) || value['fundingId'] === undefined) return false;
    if (!('change' in value) || value['change'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('positionSize' in value) || value['positionSize'] === undefined) return false;
    if (!('positionSide' in value) || value['positionSide'] === undefined) return false;
    return true;
}

export function PositionFundingFromJSON(json: any): PositionFunding {
    return PositionFundingFromJSONTyped(json, false);
}

export function PositionFundingFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionFunding {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'marketId': json['market_id'],
        'fundingId': json['funding_id'],
        'change': json['change'],
        'rate': json['rate'],
        'positionSize': json['position_size'],
        'positionSide': json['position_side'],
    };
}

export function PositionFundingToJSON(json: any): PositionFunding {
    return PositionFundingToJSONTyped(json, false);
}

export function PositionFundingToJSONTyped(value?: PositionFunding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'market_id': value['marketId'],
        'funding_id': value['fundingId'],
        'change': value['change'],
        'rate': value['rate'],
        'position_size': value['positionSize'],
        'position_side': value['positionSide'],
    };
}

