/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceLevel
 */
export interface PriceLevel {
    /**
     * 
     * @type {string}
     * @memberof PriceLevel
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof PriceLevel
     */
    size: string;
}

/**
 * Check if a given object implements the PriceLevel interface.
 */
export function instanceOfPriceLevel(value: object): value is PriceLevel {
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function PriceLevelFromJSON(json: any): PriceLevel {
    return PriceLevelFromJSONTyped(json, false);
}

export function PriceLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceLevel {
    if (json == null) {
        return json;
    }
    return {
        
        'price': json['price'],
        'size': json['size'],
    };
}

export function PriceLevelToJSON(json: any): PriceLevel {
    return PriceLevelToJSONTyped(json, false);
}

export function PriceLevelToJSONTyped(value?: PriceLevel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price': value['price'],
        'size': value['size'],
    };
}

