/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicPoolInfo } from './PublicPoolInfo';
import {
    PublicPoolInfoFromJSON,
    PublicPoolInfoFromJSONTyped,
    PublicPoolInfoToJSON,
    PublicPoolInfoToJSONTyped,
} from './PublicPoolInfo';
import type { PublicPoolShare } from './PublicPoolShare';
import {
    PublicPoolShareFromJSON,
    PublicPoolShareFromJSONTyped,
    PublicPoolShareToJSON,
    PublicPoolShareToJSONTyped,
} from './PublicPoolShare';

/**
 * 
 * @export
 * @interface PublicPool
 */
export interface PublicPool {
    /**
     * 
     * @type {number}
     * @memberof PublicPool
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof PublicPool
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof PublicPool
     */
    accountType: number;
    /**
     * 
     * @type {number}
     * @memberof PublicPool
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof PublicPool
     */
    l1Address: string;
    /**
     * 
     * @type {number}
     * @memberof PublicPool
     */
    cancelAllTime: number;
    /**
     * 
     * @type {number}
     * @memberof PublicPool
     */
    totalOrderCount: number;
    /**
     * 
     * @type {number}
     * @memberof PublicPool
     */
    pendingOrderCount: number;
    /**
     * 
     * @type {number}
     * @memberof PublicPool
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof PublicPool
     */
    collateral: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPool
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPool
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPool
     */
    totalAssetValue: string;
    /**
     * 
     * @type {PublicPoolInfo}
     * @memberof PublicPool
     */
    poolInfo: PublicPoolInfo;
    /**
     * 
     * @type {PublicPoolShare}
     * @memberof PublicPool
     */
    accountShare: PublicPoolShare;
}

/**
 * Check if a given object implements the PublicPool interface.
 */
export function instanceOfPublicPool(value: object): value is PublicPool {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('l1Address' in value) || value['l1Address'] === undefined) return false;
    if (!('cancelAllTime' in value) || value['cancelAllTime'] === undefined) return false;
    if (!('totalOrderCount' in value) || value['totalOrderCount'] === undefined) return false;
    if (!('pendingOrderCount' in value) || value['pendingOrderCount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('collateral' in value) || value['collateral'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('totalAssetValue' in value) || value['totalAssetValue'] === undefined) return false;
    if (!('poolInfo' in value) || value['poolInfo'] === undefined) return false;
    if (!('accountShare' in value) || value['accountShare'] === undefined) return false;
    return true;
}

export function PublicPoolFromJSON(json: any): PublicPool {
    return PublicPoolFromJSONTyped(json, false);
}

export function PublicPoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPool {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'accountType': json['account_type'],
        'index': json['index'],
        'l1Address': json['l1_address'],
        'cancelAllTime': json['cancel_all_time'],
        'totalOrderCount': json['total_order_count'],
        'pendingOrderCount': json['pending_order_count'],
        'status': json['status'],
        'collateral': json['collateral'],
        'name': json['name'],
        'description': json['description'],
        'totalAssetValue': json['total_asset_value'],
        'poolInfo': PublicPoolInfoFromJSON(json['pool_info']),
        'accountShare': PublicPoolShareFromJSON(json['account_share']),
    };
}

export function PublicPoolToJSON(json: any): PublicPool {
    return PublicPoolToJSONTyped(json, false);
}

export function PublicPoolToJSONTyped(value?: PublicPool | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'account_type': value['accountType'],
        'index': value['index'],
        'l1_address': value['l1Address'],
        'cancel_all_time': value['cancelAllTime'],
        'total_order_count': value['totalOrderCount'],
        'pending_order_count': value['pendingOrderCount'],
        'status': value['status'],
        'collateral': value['collateral'],
        'name': value['name'],
        'description': value['description'],
        'total_asset_value': value['totalAssetValue'],
        'pool_info': PublicPoolInfoToJSON(value['poolInfo']),
        'account_share': PublicPoolShareToJSON(value['accountShare']),
    };
}

