/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetLatestDeposit
 */
export interface ReqGetLatestDeposit {
    /**
     * 
     * @type {string}
     * @memberof ReqGetLatestDeposit
     */
    l1Address: string;
}

/**
 * Check if a given object implements the ReqGetLatestDeposit interface.
 */
export function instanceOfReqGetLatestDeposit(value: object): value is ReqGetLatestDeposit {
    if (!('l1Address' in value) || value['l1Address'] === undefined) return false;
    return true;
}

export function ReqGetLatestDepositFromJSON(json: any): ReqGetLatestDeposit {
    return ReqGetLatestDepositFromJSONTyped(json, false);
}

export function ReqGetLatestDepositFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetLatestDeposit {
    if (json == null) {
        return json;
    }
    return {
        
        'l1Address': json['l1_address'],
    };
}

export function ReqGetLatestDepositToJSON(json: any): ReqGetLatestDeposit {
    return ReqGetLatestDepositToJSONTyped(json, false);
}

export function ReqGetLatestDepositToJSONTyped(value?: ReqGetLatestDeposit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'l1_address': value['l1Address'],
    };
}

