/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetNextNonce
 */
export interface ReqGetNextNonce {
    /**
     * 
     * @type {number}
     * @memberof ReqGetNextNonce
     */
    accountIndex: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetNextNonce
     */
    apiKeyIndex: number;
}

/**
 * Check if a given object implements the ReqGetNextNonce interface.
 */
export function instanceOfReqGetNextNonce(value: object): value is ReqGetNextNonce {
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    if (!('apiKeyIndex' in value) || value['apiKeyIndex'] === undefined) return false;
    return true;
}

export function ReqGetNextNonceFromJSON(json: any): ReqGetNextNonce {
    return ReqGetNextNonceFromJSONTyped(json, false);
}

export function ReqGetNextNonceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetNextNonce {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIndex': json['account_index'],
        'apiKeyIndex': json['api_key_index'],
    };
}

export function ReqGetNextNonceToJSON(json: any): ReqGetNextNonce {
    return ReqGetNextNonceToJSONTyped(json, false);
}

export function ReqGetNextNonceToJSONTyped(value?: ReqGetNextNonce | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_index': value['accountIndex'],
        'api_key_index': value['apiKeyIndex'],
    };
}

