/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetRangeWithCursor
 */
export interface ReqGetRangeWithCursor {
    /**
     * 
     * @type {string}
     * @memberof ReqGetRangeWithCursor
     */
    cursor?: string;
    /**
     * 
     * @type {number}
     * @memberof ReqGetRangeWithCursor
     */
    limit: number;
}

/**
 * Check if a given object implements the ReqGetRangeWithCursor interface.
 */
export function instanceOfReqGetRangeWithCursor(value: object): value is ReqGetRangeWithCursor {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ReqGetRangeWithCursorFromJSON(json: any): ReqGetRangeWithCursor {
    return ReqGetRangeWithCursorFromJSONTyped(json, false);
}

export function ReqGetRangeWithCursorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetRangeWithCursor {
    if (json == null) {
        return json;
    }
    return {
        
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'limit': json['limit'],
    };
}

export function ReqGetRangeWithCursorToJSON(json: any): ReqGetRangeWithCursor {
    return ReqGetRangeWithCursorToJSONTyped(json, false);
}

export function ReqGetRangeWithCursorToJSONTyped(value?: ReqGetRangeWithCursor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cursor': value['cursor'],
        'limit': value['limit'],
    };
}

