/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetAccountOrders
 */
export interface ReqGetAccountOrders {
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountOrders
     */
    accountIndex: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountOrders
     */
    marketId: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountOrders
     */
    cursor?: string;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountOrders
     */
    limit: number;
}

/**
 * Check if a given object implements the ReqGetAccountOrders interface.
 */
export function instanceOfReqGetAccountOrders(value: object): value is ReqGetAccountOrders {
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    if (!('marketId' in value) || value['marketId'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ReqGetAccountOrdersFromJSON(json: any): ReqGetAccountOrders {
    return ReqGetAccountOrdersFromJSONTyped(json, false);
}

export function ReqGetAccountOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAccountOrders {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIndex': json['account_index'],
        'marketId': json['market_id'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'limit': json['limit'],
    };
}

export function ReqGetAccountOrdersToJSON(json: any): ReqGetAccountOrders {
    return ReqGetAccountOrdersToJSONTyped(json, false);
}

export function ReqGetAccountOrdersToJSONTyped(value?: ReqGetAccountOrders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_index': value['accountIndex'],
        'market_id': value['marketId'],
        'cursor': value['cursor'],
        'limit': value['limit'],
    };
}

