/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetWithdrawHistory
 */
export interface ReqGetWithdrawHistory {
    /**
     * 
     * @type {number}
     * @memberof ReqGetWithdrawHistory
     */
    accountIndex: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetWithdrawHistory
     */
    cursor?: string;
    /**
     * 
     * @type {string}
     * @memberof ReqGetWithdrawHistory
     */
    filter?: ReqGetWithdrawHistoryFilterEnum;
}


/**
 * @export
 */
export const ReqGetWithdrawHistoryFilterEnum = {
    all: 'all',
    pending: 'pending',
    claimable: 'claimable'
} as const;
export type ReqGetWithdrawHistoryFilterEnum = typeof ReqGetWithdrawHistoryFilterEnum[keyof typeof ReqGetWithdrawHistoryFilterEnum];


/**
 * Check if a given object implements the ReqGetWithdrawHistory interface.
 */
export function instanceOfReqGetWithdrawHistory(value: object): value is ReqGetWithdrawHistory {
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    return true;
}

export function ReqGetWithdrawHistoryFromJSON(json: any): ReqGetWithdrawHistory {
    return ReqGetWithdrawHistoryFromJSONTyped(json, false);
}

export function ReqGetWithdrawHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetWithdrawHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIndex': json['account_index'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'filter': json['filter'] == null ? undefined : json['filter'],
    };
}

export function ReqGetWithdrawHistoryToJSON(json: any): ReqGetWithdrawHistory {
    return ReqGetWithdrawHistoryToJSONTyped(json, false);
}

export function ReqGetWithdrawHistoryToJSONTyped(value?: ReqGetWithdrawHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_index': value['accountIndex'],
        'cursor': value['cursor'],
        'filter': value['filter'],
    };
}

