/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetPublicPools
 */
export interface ReqGetPublicPools {
    /**
     * 
     * @type {string}
     * @memberof ReqGetPublicPools
     */
    filter?: ReqGetPublicPoolsFilterEnum;
    /**
     * 
     * @type {number}
     * @memberof ReqGetPublicPools
     */
    index: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetPublicPools
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetPublicPools
     */
    accountIndex?: number;
}


/**
 * @export
 */
export const ReqGetPublicPoolsFilterEnum = {
    all: 'all',
    user: 'user',
    protocol: 'protocol',
    accountIndex: 'account_index'
} as const;
export type ReqGetPublicPoolsFilterEnum = typeof ReqGetPublicPoolsFilterEnum[keyof typeof ReqGetPublicPoolsFilterEnum];


/**
 * Check if a given object implements the ReqGetPublicPools interface.
 */
export function instanceOfReqGetPublicPools(value: object): value is ReqGetPublicPools {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ReqGetPublicPoolsFromJSON(json: any): ReqGetPublicPools {
    return ReqGetPublicPoolsFromJSONTyped(json, false);
}

export function ReqGetPublicPoolsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetPublicPools {
    if (json == null) {
        return json;
    }
    return {
        
        'filter': json['filter'] == null ? undefined : json['filter'],
        'index': json['index'],
        'limit': json['limit'],
        'accountIndex': json['account_index'] == null ? undefined : json['account_index'],
    };
}

export function ReqGetPublicPoolsToJSON(json: any): ReqGetPublicPools {
    return ReqGetPublicPoolsToJSONTyped(json, false);
}

export function ReqGetPublicPoolsToJSONTyped(value?: ReqGetPublicPools | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter': value['filter'],
        'index': value['index'],
        'limit': value['limit'],
        'account_index': value['accountIndex'],
    };
}

