/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetAccountApiKeys
 */
export interface ReqGetAccountApiKeys {
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountApiKeys
     */
    accountIndex: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountApiKeys
     */
    apiKeyIndex: number;
}

/**
 * Check if a given object implements the ReqGetAccountApiKeys interface.
 */
export function instanceOfReqGetAccountApiKeys(value: object): value is ReqGetAccountApiKeys {
    if (!('accountIndex' in value) || value['accountIndex'] === undefined) return false;
    if (!('apiKeyIndex' in value) || value['apiKeyIndex'] === undefined) return false;
    return true;
}

export function ReqGetAccountApiKeysFromJSON(json: any): ReqGetAccountApiKeys {
    return ReqGetAccountApiKeysFromJSONTyped(json, false);
}

export function ReqGetAccountApiKeysFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAccountApiKeys {
    if (json == null) {
        return json;
    }
    return {
        
        'accountIndex': json['account_index'],
        'apiKeyIndex': json['api_key_index'],
    };
}

export function ReqGetAccountApiKeysToJSON(json: any): ReqGetAccountApiKeys {
    return ReqGetAccountApiKeysToJSONTyped(json, false);
}

export function ReqGetAccountApiKeysToJSONTyped(value?: ReqGetAccountApiKeys | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_index': value['accountIndex'],
        'api_key_index': value['apiKeyIndex'],
    };
}

