/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetCandlesticks
 */
export interface ReqGetCandlesticks {
    /**
     * 
     * @type {number}
     * @memberof ReqGetCandlesticks
     */
    marketId: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetCandlesticks
     */
    resolution: ReqGetCandlesticksResolutionEnum;
    /**
     * 
     * @type {number}
     * @memberof ReqGetCandlesticks
     */
    startTimestamp: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetCandlesticks
     */
    endTimestamp: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetCandlesticks
     */
    countBack: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReqGetCandlesticks
     */
    setTimestampToEnd?: boolean;
}


/**
 * @export
 */
export const ReqGetCandlesticksResolutionEnum = {
    _1m: '1m',
    _5m: '5m',
    _15m: '15m',
    _1h: '1h',
    _4h: '4h',
    _1d: '1d'
} as const;
export type ReqGetCandlesticksResolutionEnum = typeof ReqGetCandlesticksResolutionEnum[keyof typeof ReqGetCandlesticksResolutionEnum];


/**
 * Check if a given object implements the ReqGetCandlesticks interface.
 */
export function instanceOfReqGetCandlesticks(value: object): value is ReqGetCandlesticks {
    if (!('marketId' in value) || value['marketId'] === undefined) return false;
    if (!('resolution' in value) || value['resolution'] === undefined) return false;
    if (!('startTimestamp' in value) || value['startTimestamp'] === undefined) return false;
    if (!('endTimestamp' in value) || value['endTimestamp'] === undefined) return false;
    if (!('countBack' in value) || value['countBack'] === undefined) return false;
    return true;
}

export function ReqGetCandlesticksFromJSON(json: any): ReqGetCandlesticks {
    return ReqGetCandlesticksFromJSONTyped(json, false);
}

export function ReqGetCandlesticksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetCandlesticks {
    if (json == null) {
        return json;
    }
    return {
        
        'marketId': json['market_id'],
        'resolution': json['resolution'],
        'startTimestamp': json['start_timestamp'],
        'endTimestamp': json['end_timestamp'],
        'countBack': json['count_back'],
        'setTimestampToEnd': json['set_timestamp_to_end'] == null ? undefined : json['set_timestamp_to_end'],
    };
}

export function ReqGetCandlesticksToJSON(json: any): ReqGetCandlesticks {
    return ReqGetCandlesticksToJSONTyped(json, false);
}

export function ReqGetCandlesticksToJSONTyped(value?: ReqGetCandlesticks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'market_id': value['marketId'],
        'resolution': value['resolution'],
        'start_timestamp': value['startTimestamp'],
        'end_timestamp': value['endTimestamp'],
        'count_back': value['countBack'],
        'set_timestamp_to_end': value['setTimestampToEnd'],
    };
}

