/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetL1Tx
 */
export interface ReqGetL1Tx {
    /**
     * 
     * @type {string}
     * @memberof ReqGetL1Tx
     */
    hash: string;
}

/**
 * Check if a given object implements the ReqGetL1Tx interface.
 */
export function instanceOfReqGetL1Tx(value: object): value is ReqGetL1Tx {
    if (!('hash' in value) || value['hash'] === undefined) return false;
    return true;
}

export function ReqGetL1TxFromJSON(json: any): ReqGetL1Tx {
    return ReqGetL1TxFromJSONTyped(json, false);
}

export function ReqGetL1TxFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetL1Tx {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'],
    };
}

export function ReqGetL1TxToJSON(json: any): ReqGetL1Tx {
    return ReqGetL1TxToJSONTyped(json, false);
}

export function ReqGetL1TxToJSONTyped(value?: ReqGetL1Tx | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hash': value['hash'],
    };
}

