/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetRangeWithIndex
 */
export interface ReqGetRangeWithIndex {
    /**
     * 
     * @type {number}
     * @memberof ReqGetRangeWithIndex
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetRangeWithIndex
     */
    limit: number;
}

/**
 * Check if a given object implements the ReqGetRangeWithIndex interface.
 */
export function instanceOfReqGetRangeWithIndex(value: object): value is ReqGetRangeWithIndex {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function ReqGetRangeWithIndexFromJSON(json: any): ReqGetRangeWithIndex {
    return ReqGetRangeWithIndexFromJSONTyped(json, false);
}

export function ReqGetRangeWithIndexFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetRangeWithIndex {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'limit': json['limit'],
    };
}

export function ReqGetRangeWithIndexToJSON(json: any): ReqGetRangeWithIndex {
    return ReqGetRangeWithIndexToJSONTyped(json, false);
}

export function ReqGetRangeWithIndexToJSONTyped(value?: ReqGetRangeWithIndex | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'limit': value['limit'],
    };
}

