/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetAccountPendingTxs
 */
export interface ReqGetAccountPendingTxs {
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountPendingTxs
     */
    by?: ReqGetAccountPendingTxsByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountPendingTxs
     */
    value?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ReqGetAccountPendingTxs
     */
    types?: Array<number>;
}


/**
 * @export
 */
export const ReqGetAccountPendingTxsByEnum = {
    accountIndex: 'account_index'
} as const;
export type ReqGetAccountPendingTxsByEnum = typeof ReqGetAccountPendingTxsByEnum[keyof typeof ReqGetAccountPendingTxsByEnum];


/**
 * Check if a given object implements the ReqGetAccountPendingTxs interface.
 */
export function instanceOfReqGetAccountPendingTxs(value: object): value is ReqGetAccountPendingTxs {
    return true;
}

export function ReqGetAccountPendingTxsFromJSON(json: any): ReqGetAccountPendingTxs {
    return ReqGetAccountPendingTxsFromJSONTyped(json, false);
}

export function ReqGetAccountPendingTxsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAccountPendingTxs {
    if (json == null) {
        return json;
    }
    return {
        
        'by': json['by'] == null ? undefined : json['by'],
        'value': json['value'] == null ? undefined : json['value'],
        'types': json['types'] == null ? undefined : json['types'],
    };
}

export function ReqGetAccountPendingTxsToJSON(json: any): ReqGetAccountPendingTxs {
    return ReqGetAccountPendingTxsToJSONTyped(json, false);
}

export function ReqGetAccountPendingTxsToJSONTyped(value?: ReqGetAccountPendingTxs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by': value['by'],
        'value': value['value'],
        'types': value['types'],
    };
}

