/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetRangeWithIndexSortable
 */
export interface ReqGetRangeWithIndexSortable {
    /**
     * 
     * @type {number}
     * @memberof ReqGetRangeWithIndexSortable
     */
    index?: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetRangeWithIndexSortable
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof ReqGetRangeWithIndexSortable
     */
    sort?: ReqGetRangeWithIndexSortableSortEnum;
}


/**
 * @export
 */
export const ReqGetRangeWithIndexSortableSortEnum = {
    asc: 'asc',
    desc: 'desc'
} as const;
export type ReqGetRangeWithIndexSortableSortEnum = typeof ReqGetRangeWithIndexSortableSortEnum[keyof typeof ReqGetRangeWithIndexSortableSortEnum];


/**
 * Check if a given object implements the ReqGetRangeWithIndexSortable interface.
 */
export function instanceOfReqGetRangeWithIndexSortable(value: object): value is ReqGetRangeWithIndexSortable {
    return true;
}

export function ReqGetRangeWithIndexSortableFromJSON(json: any): ReqGetRangeWithIndexSortable {
    return ReqGetRangeWithIndexSortableFromJSONTyped(json, false);
}

export function ReqGetRangeWithIndexSortableFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetRangeWithIndexSortable {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'sort': json['sort'] == null ? undefined : json['sort'],
    };
}

export function ReqGetRangeWithIndexSortableToJSON(json: any): ReqGetRangeWithIndexSortable {
    return ReqGetRangeWithIndexSortableToJSONTyped(json, false);
}

export function ReqGetRangeWithIndexSortableToJSONTyped(value?: ReqGetRangeWithIndexSortable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'limit': value['limit'],
        'sort': value['sort'],
    };
}

