/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReqGetAccountPnL
 */
export interface ReqGetAccountPnL {
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountPnL
     */
    by: ReqGetAccountPnLByEnum;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountPnL
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof ReqGetAccountPnL
     */
    resolution: ReqGetAccountPnLResolutionEnum;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountPnL
     */
    startTimestamp: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountPnL
     */
    endTimestamp: number;
    /**
     * 
     * @type {number}
     * @memberof ReqGetAccountPnL
     */
    countBack: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReqGetAccountPnL
     */
    ignoreTransfers?: boolean;
}


/**
 * @export
 */
export const ReqGetAccountPnLByEnum = {
    index: 'index'
} as const;
export type ReqGetAccountPnLByEnum = typeof ReqGetAccountPnLByEnum[keyof typeof ReqGetAccountPnLByEnum];

/**
 * @export
 */
export const ReqGetAccountPnLResolutionEnum = {
    _1m: '1m',
    _5m: '5m',
    _15m: '15m',
    _1h: '1h',
    _4h: '4h',
    _1d: '1d'
} as const;
export type ReqGetAccountPnLResolutionEnum = typeof ReqGetAccountPnLResolutionEnum[keyof typeof ReqGetAccountPnLResolutionEnum];


/**
 * Check if a given object implements the ReqGetAccountPnL interface.
 */
export function instanceOfReqGetAccountPnL(value: object): value is ReqGetAccountPnL {
    if (!('by' in value) || value['by'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('resolution' in value) || value['resolution'] === undefined) return false;
    if (!('startTimestamp' in value) || value['startTimestamp'] === undefined) return false;
    if (!('endTimestamp' in value) || value['endTimestamp'] === undefined) return false;
    if (!('countBack' in value) || value['countBack'] === undefined) return false;
    return true;
}

export function ReqGetAccountPnLFromJSON(json: any): ReqGetAccountPnL {
    return ReqGetAccountPnLFromJSONTyped(json, false);
}

export function ReqGetAccountPnLFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReqGetAccountPnL {
    if (json == null) {
        return json;
    }
    return {
        
        'by': json['by'],
        'value': json['value'],
        'resolution': json['resolution'],
        'startTimestamp': json['start_timestamp'],
        'endTimestamp': json['end_timestamp'],
        'countBack': json['count_back'],
        'ignoreTransfers': json['ignore_transfers'] == null ? undefined : json['ignore_transfers'],
    };
}

export function ReqGetAccountPnLToJSON(json: any): ReqGetAccountPnL {
    return ReqGetAccountPnLToJSONTyped(json, false);
}

export function ReqGetAccountPnLToJSONTyped(value?: ReqGetAccountPnL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'by': value['by'],
        'value': value['value'],
        'resolution': value['resolution'],
        'start_timestamp': value['startTimestamp'],
        'end_timestamp': value['endTimestamp'],
        'count_back': value['countBack'],
        'ignore_transfers': value['ignoreTransfers'],
    };
}

