/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceLevel } from './PriceLevel';
import {
    PriceLevelFromJSON,
    PriceLevelFromJSONTyped,
    PriceLevelToJSON,
    PriceLevelToJSONTyped,
} from './PriceLevel';

/**
 * 
 * @export
 * @interface Ticker
 */
export interface Ticker {
    /**
     * 
     * @type {string}
     * @memberof Ticker
     */
    s: string;
    /**
     * 
     * @type {PriceLevel}
     * @memberof Ticker
     */
    a: PriceLevel;
    /**
     * 
     * @type {PriceLevel}
     * @memberof Ticker
     */
    b: PriceLevel;
}

/**
 * Check if a given object implements the Ticker interface.
 */
export function instanceOfTicker(value: object): value is Ticker {
    if (!('s' in value) || value['s'] === undefined) return false;
    if (!('a' in value) || value['a'] === undefined) return false;
    if (!('b' in value) || value['b'] === undefined) return false;
    return true;
}

export function TickerFromJSON(json: any): Ticker {
    return TickerFromJSONTyped(json, false);
}

export function TickerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ticker {
    if (json == null) {
        return json;
    }
    return {
        
        's': json['s'],
        'a': PriceLevelFromJSON(json['a']),
        'b': PriceLevelFromJSON(json['b']),
    };
}

export function TickerToJSON(json: any): Ticker {
    return TickerToJSONTyped(json, false);
}

export function TickerToJSONTyped(value?: Ticker | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        's': value['s'],
        'a': PriceLevelToJSON(value['a']),
        'b': PriceLevelToJSON(value['b']),
    };
}

