/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TxHashes
 */
export interface TxHashes {
    /**
     * 
     * @type {number}
     * @memberof TxHashes
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof TxHashes
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TxHashes
     */
    txHash: Array<string>;
}

/**
 * Check if a given object implements the TxHashes interface.
 */
export function instanceOfTxHashes(value: object): value is TxHashes {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    return true;
}

export function TxHashesFromJSON(json: any): TxHashes {
    return TxHashesFromJSONTyped(json, false);
}

export function TxHashesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxHashes {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'txHash': json['tx_hash'],
    };
}

export function TxHashesToJSON(json: any): TxHashes {
    return TxHashesToJSONTyped(json, false);
}

export function TxHashesToJSONTyped(value?: TxHashes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'tx_hash': value['txHash'],
    };
}

