/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TxHash
 */
export interface TxHash {
    /**
     * 
     * @type {number}
     * @memberof TxHash
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof TxHash
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TxHash
     */
    txHash: string;
}

/**
 * Check if a given object implements the TxHash interface.
 */
export function instanceOfTxHash(value: object): value is TxHash {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    return true;
}

export function TxHashFromJSON(json: any): TxHash {
    return TxHashFromJSONTyped(json, false);
}

export function TxHashFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxHash {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'txHash': json['tx_hash'],
    };
}

export function TxHashToJSON(json: any): TxHash {
    return TxHashToJSONTyped(json, false);
}

export function TxHashToJSONTyped(value?: TxHash | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'tx_hash': value['txHash'],
    };
}

