/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tx } from './Tx';
import {
    TxFromJSON,
    TxFromJSONTyped,
    TxToJSON,
    TxToJSONTyped,
} from './Tx';

/**
 * 
 * @export
 * @interface Txs
 */
export interface Txs {
    /**
     * 
     * @type {number}
     * @memberof Txs
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof Txs
     */
    message?: string;
    /**
     * 
     * @type {Array<Tx>}
     * @memberof Txs
     */
    txs: Array<Tx>;
}

/**
 * Check if a given object implements the Txs interface.
 */
export function instanceOfTxs(value: object): value is Txs {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('txs' in value) || value['txs'] === undefined) return false;
    return true;
}

export function TxsFromJSON(json: any): Txs {
    return TxsFromJSONTyped(json, false);
}

export function TxsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Txs {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'txs': ((json['txs'] as Array<any>).map(TxFromJSON)),
    };
}

export function TxsToJSON(json: any): Txs {
    return TxsToJSONTyped(json, false);
}

export function TxsToJSONTyped(value?: Txs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'txs': ((value['txs'] as Array<any>).map(TxToJSON)),
    };
}

