/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WithdrawHistoryItem
 */
export interface WithdrawHistoryItem {
    /**
     * 
     * @type {string}
     * @memberof WithdrawHistoryItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawHistoryItem
     */
    amount: string;
    /**
     * 
     * @type {number}
     * @memberof WithdrawHistoryItem
     */
    timestamp: number;
    /**
     * 
     * @type {string}
     * @memberof WithdrawHistoryItem
     */
    status: WithdrawHistoryItemStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WithdrawHistoryItem
     */
    type: WithdrawHistoryItemTypeEnum;
}


/**
 * @export
 */
export const WithdrawHistoryItemStatusEnum = {
    failed: 'failed',
    pending: 'pending',
    claimable: 'claimable',
    refunded: 'refunded',
    completed: 'completed'
} as const;
export type WithdrawHistoryItemStatusEnum = typeof WithdrawHistoryItemStatusEnum[keyof typeof WithdrawHistoryItemStatusEnum];

/**
 * @export
 */
export const WithdrawHistoryItemTypeEnum = {
    secure: 'secure',
    fast: 'fast'
} as const;
export type WithdrawHistoryItemTypeEnum = typeof WithdrawHistoryItemTypeEnum[keyof typeof WithdrawHistoryItemTypeEnum];


/**
 * Check if a given object implements the WithdrawHistoryItem interface.
 */
export function instanceOfWithdrawHistoryItem(value: object): value is WithdrawHistoryItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function WithdrawHistoryItemFromJSON(json: any): WithdrawHistoryItem {
    return WithdrawHistoryItemFromJSONTyped(json, false);
}

export function WithdrawHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawHistoryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'timestamp': json['timestamp'],
        'status': json['status'],
        'type': json['type'],
    };
}

export function WithdrawHistoryItemToJSON(json: any): WithdrawHistoryItem {
    return WithdrawHistoryItemToJSONTyped(json, false);
}

export function WithdrawHistoryItemToJSONTyped(value?: WithdrawHistoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'timestamp': value['timestamp'],
        'status': value['status'],
        'type': value['type'],
    };
}

