/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WithdrawHistoryCursor
 */
export interface WithdrawHistoryCursor {
    /**
     * 
     * @type {string}
     * @memberof WithdrawHistoryCursor
     */
    secureId: string;
    /**
     * 
     * @type {string}
     * @memberof WithdrawHistoryCursor
     */
    fastId: string;
}

/**
 * Check if a given object implements the WithdrawHistoryCursor interface.
 */
export function instanceOfWithdrawHistoryCursor(value: object): value is WithdrawHistoryCursor {
    if (!('secureId' in value) || value['secureId'] === undefined) return false;
    if (!('fastId' in value) || value['fastId'] === undefined) return false;
    return true;
}

export function WithdrawHistoryCursorFromJSON(json: any): WithdrawHistoryCursor {
    return WithdrawHistoryCursorFromJSONTyped(json, false);
}

export function WithdrawHistoryCursorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WithdrawHistoryCursor {
    if (json == null) {
        return json;
    }
    return {
        
        'secureId': json['secure_id'],
        'fastId': json['fast_id'],
    };
}

export function WithdrawHistoryCursorToJSON(json: any): WithdrawHistoryCursor {
    return WithdrawHistoryCursorToJSONTyped(json, false);
}

export function WithdrawHistoryCursorToJSONTyped(value?: WithdrawHistoryCursor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secure_id': value['secureId'],
        'fast_id': value['fastId'],
    };
}

